// Code generated by protoc-gen-go-resource. DO NOT EDIT.
// source: multipattern/multipattern.proto

package multipattern

import (
	errors "errors"
	fmt "fmt"
	strings "strings"
)

// PublisherName is the parsed form of a "example.com/Publisher" resource name (pattern "publishers/{publisher}").
type PublisherName struct {
	PublisherID string
}

// ParsePublisherName parses s as PublisherName (pattern "publishers/{publisher}").
func ParsePublisherName(s string) (PublisherName, error) {
	parts := strings.Split(s, "/")
	if len(parts) != 2 {
		return PublisherName{}, fmt.Errorf("parse %q: bad number of segments, want: 2, got: %d", s, len(parts))
	}
	var out PublisherName
	if parts[0] != "publishers" {
		return PublisherName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "publishers", parts[0])
	}
	if parts[1] == "" {
		return PublisherName{}, fmt.Errorf("parse %q: empty value for segment 1", s)
	}
	out.PublisherID = parts[1]
	return out, nil
}

// ParseFullPublisherName parses s as the fully-qualified form of PublisherName (prefix "//example.com/").
func ParseFullPublisherName(s string) (PublisherName, error) {
	if !strings.HasPrefix(s, "//example.com/") {
		return PublisherName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//example.com/")
	}
	return ParsePublisherName(strings.TrimPrefix(s, "//example.com/"))
}

// String returns the relative resource name "publishers/{publisher}" and implements fmt.Stringer.
func (n PublisherName) String() string {
	return "publishers/" + n.PublisherID
}

// FullName returns the fully-qualified resource name prefixed with "//example.com/".
func (n PublisherName) FullName() string {
	return "//example.com/" + n.String()
}

// MarshalText implements encoding.TextMarshaler and emits the relative resource name.
func (n PublisherName) MarshalText() ([]byte, error) {
	return []byte(n.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler by parsing b as a relative PublisherName.
func (n *PublisherName) UnmarshalText(b []byte) error {
	parsed, err := ParsePublisherName(string(b))
	if err != nil {
		return err
	}
	*n = parsed
	return nil
}

// AuthorName is the parsed form of a "example.com/Author" resource name (pattern "authors/{author}").
type AuthorName struct {
	AuthorID string
}

// ParseAuthorName parses s as AuthorName (pattern "authors/{author}").
func ParseAuthorName(s string) (AuthorName, error) {
	parts := strings.Split(s, "/")
	if len(parts) != 2 {
		return AuthorName{}, fmt.Errorf("parse %q: bad number of segments, want: 2, got: %d", s, len(parts))
	}
	var out AuthorName
	if parts[0] != "authors" {
		return AuthorName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "authors", parts[0])
	}
	if parts[1] == "" {
		return AuthorName{}, fmt.Errorf("parse %q: empty value for segment 1", s)
	}
	out.AuthorID = parts[1]
	return out, nil
}

// ParseFullAuthorName parses s as the fully-qualified form of AuthorName (prefix "//example.com/").
func ParseFullAuthorName(s string) (AuthorName, error) {
	if !strings.HasPrefix(s, "//example.com/") {
		return AuthorName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//example.com/")
	}
	return ParseAuthorName(strings.TrimPrefix(s, "//example.com/"))
}

// String returns the relative resource name "authors/{author}" and implements fmt.Stringer.
func (n AuthorName) String() string {
	return "authors/" + n.AuthorID
}

// FullName returns the fully-qualified resource name prefixed with "//example.com/".
func (n AuthorName) FullName() string {
	return "//example.com/" + n.String()
}

// MarshalText implements encoding.TextMarshaler and emits the relative resource name.
func (n AuthorName) MarshalText() ([]byte, error) {
	return []byte(n.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler by parsing b as a relative AuthorName.
func (n *AuthorName) UnmarshalText(b []byte) error {
	parsed, err := ParseAuthorName(string(b))
	if err != nil {
		return err
	}
	*n = parsed
	return nil
}

// PublisherBookName is the "publishers/{publisher}/books/{book}" variant of BookName.
type PublisherBookName struct {
	PublisherID string
	BookID      string
}

// ParsePublisherBookName parses s as PublisherBookName (pattern "publishers/{publisher}/books/{book}").
func ParsePublisherBookName(s string) (PublisherBookName, error) {
	parts := strings.Split(s, "/")
	if len(parts) != 4 {
		return PublisherBookName{}, fmt.Errorf("parse %q: bad number of segments, want: 4, got: %d", s, len(parts))
	}
	var out PublisherBookName
	if parts[0] != "publishers" {
		return PublisherBookName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "publishers", parts[0])
	}
	if parts[1] == "" {
		return PublisherBookName{}, fmt.Errorf("parse %q: empty value for segment 1", s)
	}
	out.PublisherID = parts[1]
	if parts[2] != "books" {
		return PublisherBookName{}, fmt.Errorf("parse %q: bad segment 2, want: %q, got: %q", s, "books", parts[2])
	}
	if parts[3] == "" {
		return PublisherBookName{}, fmt.Errorf("parse %q: empty value for segment 3", s)
	}
	out.BookID = parts[3]
	return out, nil
}

// String returns the relative resource name "publishers/{publisher}/books/{book}" and implements fmt.Stringer.
func (n PublisherBookName) String() string {
	return "publishers/" + n.PublisherID + "/books/" + n.BookID
}

// FullName returns the fully-qualified resource name prefixed with "//example.com/".
func (n PublisherBookName) FullName() string {
	return "//example.com/" + n.String()
}

// MarshalText implements encoding.TextMarshaler and emits the relative resource name.
func (n PublisherBookName) MarshalText() ([]byte, error) {
	return []byte(n.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler by parsing b as a relative PublisherBookName.
func (n *PublisherBookName) UnmarshalText(b []byte) error {
	parsed, err := ParsePublisherBookName(string(b))
	if err != nil {
		return err
	}
	*n = parsed
	return nil
}

// Parent returns the parent PublisherName derived from this resource's fields.
func (n PublisherBookName) Parent() PublisherName {
	return PublisherName{
		PublisherID: n.PublisherID,
	}
}

func (n PublisherBookName) mustEmbedBookName() {}

// AuthorBookName is the "authors/{author}/books/{book}" variant of BookName.
type AuthorBookName struct {
	AuthorID string
	BookID   string
}

// ParseAuthorBookName parses s as AuthorBookName (pattern "authors/{author}/books/{book}").
func ParseAuthorBookName(s string) (AuthorBookName, error) {
	parts := strings.Split(s, "/")
	if len(parts) != 4 {
		return AuthorBookName{}, fmt.Errorf("parse %q: bad number of segments, want: 4, got: %d", s, len(parts))
	}
	var out AuthorBookName
	if parts[0] != "authors" {
		return AuthorBookName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "authors", parts[0])
	}
	if parts[1] == "" {
		return AuthorBookName{}, fmt.Errorf("parse %q: empty value for segment 1", s)
	}
	out.AuthorID = parts[1]
	if parts[2] != "books" {
		return AuthorBookName{}, fmt.Errorf("parse %q: bad segment 2, want: %q, got: %q", s, "books", parts[2])
	}
	if parts[3] == "" {
		return AuthorBookName{}, fmt.Errorf("parse %q: empty value for segment 3", s)
	}
	out.BookID = parts[3]
	return out, nil
}

// String returns the relative resource name "authors/{author}/books/{book}" and implements fmt.Stringer.
func (n AuthorBookName) String() string {
	return "authors/" + n.AuthorID + "/books/" + n.BookID
}

// FullName returns the fully-qualified resource name prefixed with "//example.com/".
func (n AuthorBookName) FullName() string {
	return "//example.com/" + n.String()
}

// MarshalText implements encoding.TextMarshaler and emits the relative resource name.
func (n AuthorBookName) MarshalText() ([]byte, error) {
	return []byte(n.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler by parsing b as a relative AuthorBookName.
func (n *AuthorBookName) UnmarshalText(b []byte) error {
	parsed, err := ParseAuthorBookName(string(b))
	if err != nil {
		return err
	}
	*n = parsed
	return nil
}

// Parent returns the parent AuthorName derived from this resource's fields.
func (n AuthorBookName) Parent() AuthorName {
	return AuthorName{
		AuthorID: n.AuthorID,
	}
}

func (n AuthorBookName) mustEmbedBookName() {}

// BookName is the parsed form of a "example.com/Book" resource name. It is a sealed interface with one implementation per declared pattern.
type BookName interface {
	String() string
	FullName() string
	MarshalText() ([]byte, error)
	mustEmbedBookName()
}

// ParseBookName parses s as BookName, trying each pattern in declaration order and returning the first match.
func ParseBookName(s string) (BookName, error) {
	var errs []error
	{
		res, err := ParsePublisherBookName(s)
		if err == nil {
			return res, nil
		}
		errs = append(errs, err)
	}
	{
		res, err := ParseAuthorBookName(s)
		if err == nil {
			return res, nil
		}
		errs = append(errs, err)
	}
	return nil, fmt.Errorf("parse %q: no pattern matches: %w", s, errors.Join(errs...))
}

// ParseFullBookName parses the fully-qualified form of BookName (prefix "//example.com/") and delegates to ParseBookName.
func ParseFullBookName(s string) (BookName, error) {
	if !strings.HasPrefix(s, "//example.com/") {
		return nil, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//example.com/")
	}
	return ParseBookName(strings.TrimPrefix(s, "//example.com/"))
}

// ParseName parses x.Name as PublisherName.
func (x *Publisher) ParseName() (PublisherName, error) {
	return ParsePublisherName(x.Name)
}

// ParseFullName parses x.Name as PublisherName.
func (x *Publisher) ParseFullName() (PublisherName, error) {
	return ParseFullPublisherName(x.Name)
}

// ParseName parses x.Name as AuthorName.
func (x *Author) ParseName() (AuthorName, error) {
	return ParseAuthorName(x.Name)
}

// ParseFullName parses x.Name as AuthorName.
func (x *Author) ParseFullName() (AuthorName, error) {
	return ParseFullAuthorName(x.Name)
}

// ParseName parses x.Name as BookName.
func (x *Book) ParseName() (BookName, error) {
	return ParseBookName(x.Name)
}

// ParseFullName parses x.Name as BookName.
func (x *Book) ParseFullName() (BookName, error) {
	return ParseFullBookName(x.Name)
}
