// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: multipattern/multipattern.proto

package multipattern

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Book exercises a resource with more than one pattern. The generator emits a
// sealed interface and one struct per pattern; ParseBookName tries each in
// order.
type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_multipattern_multipattern_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_multipattern_multipattern_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_multipattern_multipattern_proto_rawDescGZIP(), []int{0}
}

func (x *Book) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_multipattern_multipattern_proto protoreflect.FileDescriptor

const file_multipattern_multipattern_proto_rawDesc = "" +
	"\n" +
	"\x1fmultipattern/multipattern.proto\x12\x12tests.multipattern\x1a\x19google/api/resource.proto\"u\n" +
	"\x04Book\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name:Y\xeaAV\n" +
	"\x10example.com/Book\x12#publishers/{publisher}/books/{book}\x12\x1dauthors/{author}/books/{book}BYZWgithub.com/protoc-contrib/protoc-gen-go-resource/internal/generator/testpb/multipatternb\x06proto3"

var (
	file_multipattern_multipattern_proto_rawDescOnce sync.Once
	file_multipattern_multipattern_proto_rawDescData []byte
)

func file_multipattern_multipattern_proto_rawDescGZIP() []byte {
	file_multipattern_multipattern_proto_rawDescOnce.Do(func() {
		file_multipattern_multipattern_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_multipattern_multipattern_proto_rawDesc), len(file_multipattern_multipattern_proto_rawDesc)))
	})
	return file_multipattern_multipattern_proto_rawDescData
}

var file_multipattern_multipattern_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_multipattern_multipattern_proto_goTypes = []any{
	(*Book)(nil), // 0: tests.multipattern.Book
}
var file_multipattern_multipattern_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_multipattern_multipattern_proto_init() }
func file_multipattern_multipattern_proto_init() {
	if File_multipattern_multipattern_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_multipattern_multipattern_proto_rawDesc), len(file_multipattern_multipattern_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_multipattern_multipattern_proto_goTypes,
		DependencyIndexes: file_multipattern_multipattern_proto_depIdxs,
		MessageInfos:      file_multipattern_multipattern_proto_msgTypes,
	}.Build()
	File_multipattern_multipattern_proto = out.File
	file_multipattern_multipattern_proto_goTypes = nil
	file_multipattern_multipattern_proto_depIdxs = nil
}
