// Code generated by protoc-gen-go-resource. DO NOT EDIT.
// source: multipattern/multipattern.proto

package multipattern

import (
	fmt "fmt"
	strings "strings"
)

type ParsedBookName_0 struct {
	PublisherID string
	BookID      string
}

func ParseBookName_0(s string) (ParsedBookName_0, error) {
	parts := strings.Split(s, "/")
	if len(parts) != 4 {
		return ParsedBookName_0{}, fmt.Errorf("parse %q: bad number of segments, want: 4, got: %d", s, len(parts))
	}
	var out ParsedBookName_0
	if parts[0] != "publishers" {
		return ParsedBookName_0{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "publishers", parts[0])
	}
	out.PublisherID = parts[1]
	if parts[2] != "books" {
		return ParsedBookName_0{}, fmt.Errorf("parse %q: bad segment 2, want: %q, got: %q", s, "books", parts[2])
	}
	out.BookID = parts[3]
	return out, nil
}

func ParseBookNameFull_0(s string) (ParsedBookName_0, error) {
	if !strings.HasPrefix(s, "//example.com/") {
		return ParsedBookName_0{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//example.com/")
	}
	return ParseBookName_0(strings.TrimPrefix(s, "//example.com/"))
}

func (n ParsedBookName_0) Name() string {
	return "publishers/" + n.PublisherID + "/books/" + n.BookID
}

func (n ParsedBookName_0) FullName() string {
	return "//example.com/" + n.Name()
}

func (n ParsedBookName_0) mustEmbedParsedBookName() {}

type ParsedBookName_1 struct {
	AuthorID string
	BookID   string
}

func ParseBookName_1(s string) (ParsedBookName_1, error) {
	parts := strings.Split(s, "/")
	if len(parts) != 4 {
		return ParsedBookName_1{}, fmt.Errorf("parse %q: bad number of segments, want: 4, got: %d", s, len(parts))
	}
	var out ParsedBookName_1
	if parts[0] != "authors" {
		return ParsedBookName_1{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "authors", parts[0])
	}
	out.AuthorID = parts[1]
	if parts[2] != "books" {
		return ParsedBookName_1{}, fmt.Errorf("parse %q: bad segment 2, want: %q, got: %q", s, "books", parts[2])
	}
	out.BookID = parts[3]
	return out, nil
}

func ParseBookNameFull_1(s string) (ParsedBookName_1, error) {
	if !strings.HasPrefix(s, "//example.com/") {
		return ParsedBookName_1{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//example.com/")
	}
	return ParseBookName_1(strings.TrimPrefix(s, "//example.com/"))
}

func (n ParsedBookName_1) Name() string {
	return "authors/" + n.AuthorID + "/books/" + n.BookID
}

func (n ParsedBookName_1) FullName() string {
	return "//example.com/" + n.Name()
}

func (n ParsedBookName_1) mustEmbedParsedBookName() {}

type ParsedBookName interface {
	Name() string
	FullName() string
	mustEmbedParsedBookName()
}

func ParseBookName(s string) (ParsedBookName, error) {
	var errs []string
	if res, err := ParseBookName_0(s); err == nil {
		return res, nil
	} else {
		errs = append(errs, fmt.Sprintf("pattern 0: %v", err))
	}
	if res, err := ParseBookName_1(s); err == nil {
		return res, nil
	} else {
		errs = append(errs, fmt.Sprintf("pattern 1: %v", err))
	}
	return nil, fmt.Errorf("no pattern matches input: %v", strings.Join(errs, "; "))
}

func ParseFullBookName(s string) (ParsedBookName, error) {
	if !strings.HasPrefix(s, "//example.com/") {
		return nil, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//example.com/")
	}
	return ParseBookName(strings.TrimPrefix(s, "//example.com/"))
}

func (x *Book) ParseName() (ParsedBookName, error) {
	return ParseBookName(x.Name)
}
