// Code generated by protoc-gen-go-resource. DO NOT EDIT.
// source: multipattern/multipattern.proto

package multipattern

import (
	errors "errors"
	fmt "fmt"
	strings "strings"
)

type PublisherName struct {
	PublisherID string
}

func ParsePublisherName(s string) (PublisherName, error) {
	parts := strings.Split(s, "/")
	if len(parts) != 2 {
		return PublisherName{}, fmt.Errorf("parse %q: bad number of segments, want: 2, got: %d", s, len(parts))
	}
	var out PublisherName
	if parts[0] != "publishers" {
		return PublisherName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "publishers", parts[0])
	}
	if parts[1] == "" {
		return PublisherName{}, fmt.Errorf("parse %q: empty value for segment 1", s)
	}
	out.PublisherID = parts[1]
	return out, nil
}

func ParseFullPublisherName(s string) (PublisherName, error) {
	if !strings.HasPrefix(s, "//example.com/") {
		return PublisherName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//example.com/")
	}
	return ParsePublisherName(strings.TrimPrefix(s, "//example.com/"))
}

func (n PublisherName) Name() string {
	return "publishers/" + n.PublisherID
}

func (n PublisherName) FullName() string {
	return "//example.com/" + n.Name()
}

type AuthorName struct {
	AuthorID string
}

func ParseAuthorName(s string) (AuthorName, error) {
	parts := strings.Split(s, "/")
	if len(parts) != 2 {
		return AuthorName{}, fmt.Errorf("parse %q: bad number of segments, want: 2, got: %d", s, len(parts))
	}
	var out AuthorName
	if parts[0] != "authors" {
		return AuthorName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "authors", parts[0])
	}
	if parts[1] == "" {
		return AuthorName{}, fmt.Errorf("parse %q: empty value for segment 1", s)
	}
	out.AuthorID = parts[1]
	return out, nil
}

func ParseFullAuthorName(s string) (AuthorName, error) {
	if !strings.HasPrefix(s, "//example.com/") {
		return AuthorName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//example.com/")
	}
	return ParseAuthorName(strings.TrimPrefix(s, "//example.com/"))
}

func (n AuthorName) Name() string {
	return "authors/" + n.AuthorID
}

func (n AuthorName) FullName() string {
	return "//example.com/" + n.Name()
}

type PublisherBookName struct {
	PublisherID string
	BookID      string
}

func ParsePublisherBookName(s string) (PublisherBookName, error) {
	parts := strings.Split(s, "/")
	if len(parts) != 4 {
		return PublisherBookName{}, fmt.Errorf("parse %q: bad number of segments, want: 4, got: %d", s, len(parts))
	}
	var out PublisherBookName
	if parts[0] != "publishers" {
		return PublisherBookName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "publishers", parts[0])
	}
	if parts[1] == "" {
		return PublisherBookName{}, fmt.Errorf("parse %q: empty value for segment 1", s)
	}
	out.PublisherID = parts[1]
	if parts[2] != "books" {
		return PublisherBookName{}, fmt.Errorf("parse %q: bad segment 2, want: %q, got: %q", s, "books", parts[2])
	}
	if parts[3] == "" {
		return PublisherBookName{}, fmt.Errorf("parse %q: empty value for segment 3", s)
	}
	out.BookID = parts[3]
	return out, nil
}

func (n PublisherBookName) Name() string {
	return "publishers/" + n.PublisherID + "/books/" + n.BookID
}

func (n PublisherBookName) FullName() string {
	return "//example.com/" + n.Name()
}

func (n PublisherBookName) Parent() PublisherName {
	return PublisherName{
		PublisherID: n.PublisherID,
	}
}

func (n PublisherBookName) mustEmbedBookName() {}

type AuthorBookName struct {
	AuthorID string
	BookID   string
}

func ParseAuthorBookName(s string) (AuthorBookName, error) {
	parts := strings.Split(s, "/")
	if len(parts) != 4 {
		return AuthorBookName{}, fmt.Errorf("parse %q: bad number of segments, want: 4, got: %d", s, len(parts))
	}
	var out AuthorBookName
	if parts[0] != "authors" {
		return AuthorBookName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "authors", parts[0])
	}
	if parts[1] == "" {
		return AuthorBookName{}, fmt.Errorf("parse %q: empty value for segment 1", s)
	}
	out.AuthorID = parts[1]
	if parts[2] != "books" {
		return AuthorBookName{}, fmt.Errorf("parse %q: bad segment 2, want: %q, got: %q", s, "books", parts[2])
	}
	if parts[3] == "" {
		return AuthorBookName{}, fmt.Errorf("parse %q: empty value for segment 3", s)
	}
	out.BookID = parts[3]
	return out, nil
}

func (n AuthorBookName) Name() string {
	return "authors/" + n.AuthorID + "/books/" + n.BookID
}

func (n AuthorBookName) FullName() string {
	return "//example.com/" + n.Name()
}

func (n AuthorBookName) Parent() AuthorName {
	return AuthorName{
		AuthorID: n.AuthorID,
	}
}

func (n AuthorBookName) mustEmbedBookName() {}

type BookName interface {
	Name() string
	FullName() string
	mustEmbedBookName()
}

func ParseBookName(s string) (BookName, error) {
	var errs []error
	{
		res, err := ParsePublisherBookName(s)
		if err == nil {
			return res, nil
		}
		errs = append(errs, err)
	}
	{
		res, err := ParseAuthorBookName(s)
		if err == nil {
			return res, nil
		}
		errs = append(errs, err)
	}
	return nil, fmt.Errorf("parse %q: no pattern matches: %w", s, errors.Join(errs...))
}

func ParseFullBookName(s string) (BookName, error) {
	if !strings.HasPrefix(s, "//example.com/") {
		return nil, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//example.com/")
	}
	return ParseBookName(strings.TrimPrefix(s, "//example.com/"))
}

func (x *Publisher) ParseName() (PublisherName, error) {
	return ParsePublisherName(x.Name)
}

func (x *Publisher) ParseFullName() (PublisherName, error) {
	return ParseFullPublisherName(x.Name)
}

func (x *Author) ParseName() (AuthorName, error) {
	return ParseAuthorName(x.Name)
}

func (x *Author) ParseFullName() (AuthorName, error) {
	return ParseFullAuthorName(x.Name)
}

func (x *Book) ParseName() (BookName, error) {
	return ParseBookName(x.Name)
}

func (x *Book) ParseFullName() (BookName, error) {
	return ParseFullBookName(x.Name)
}
