// Code generated by protoc-gen-go-resource. DO NOT EDIT.
// source: reference/reference.proto

package reference

import (
	fmt "fmt"
	external "github.com/protoc-contrib/protoc-gen-go-resource/internal/generator/testpb/external"
	simple "github.com/protoc-contrib/protoc-gen-go-resource/internal/generator/testpb/simple"
	strings "strings"
)

type FooName struct {
	FooID string
}

func ParseFooName(s string) (FooName, error) {
	parts := strings.Split(s, "/")
	if len(parts) != 2 {
		return FooName{}, fmt.Errorf("parse %q: bad number of segments, want: 2, got: %d", s, len(parts))
	}
	var out FooName
	if parts[0] != "foos" {
		return FooName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "foos", parts[0])
	}
	if parts[1] == "" {
		return FooName{}, fmt.Errorf("parse %q: empty value for segment 1", s)
	}
	out.FooID = parts[1]
	return out, nil
}

func ParseFullFooName(s string) (FooName, error) {
	if !strings.HasPrefix(s, "//example.com/") {
		return FooName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//example.com/")
	}
	return ParseFooName(strings.TrimPrefix(s, "//example.com/"))
}

func (n FooName) Name() string {
	return "foos/" + n.FooID
}

func (n FooName) FullName() string {
	return "//example.com/" + n.Name()
}

func (n FooName) String() string {
	return n.Name()
}

type BarName struct {
	BarID string
}

func ParseBarName(s string) (BarName, error) {
	parts := strings.Split(s, "/")
	if len(parts) != 2 {
		return BarName{}, fmt.Errorf("parse %q: bad number of segments, want: 2, got: %d", s, len(parts))
	}
	var out BarName
	if parts[0] != "bars" {
		return BarName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "bars", parts[0])
	}
	if parts[1] == "" {
		return BarName{}, fmt.Errorf("parse %q: empty value for segment 1", s)
	}
	out.BarID = parts[1]
	return out, nil
}

func ParseFullBarName(s string) (BarName, error) {
	if !strings.HasPrefix(s, "//example.com/") {
		return BarName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//example.com/")
	}
	return ParseBarName(strings.TrimPrefix(s, "//example.com/"))
}

func (n BarName) Name() string {
	return "bars/" + n.BarID
}

func (n BarName) FullName() string {
	return "//example.com/" + n.Name()
}

func (n BarName) String() string {
	return n.Name()
}

func (x *Foo) ParseName() (FooName, error) {
	return ParseFooName(x.Name)
}

func (x *Foo) ParseFullName() (FooName, error) {
	return ParseFullFooName(x.Name)
}

func (x *Foo) ParseBar() (BarName, error) {
	return ParseBarName(x.Bar)
}

func (x *Bar) ParseName() (BarName, error) {
	return ParseBarName(x.Name)
}

func (x *Bar) ParseFullName() (BarName, error) {
	return ParseFullBarName(x.Name)
}

func (x *Bar) ParseFoo() (FooName, error) {
	return ParseFooName(x.Foo)
}

func (x *CrossPackage) ParseThingName() (simple.ThingName, error) {
	return simple.ParseThingName(x.ThingName)
}

func (x *CrossPackageExternal) ParseExternalName() (external.ExternalName, error) {
	return external.ParseExternalName(x.ExternalName)
}
