// Code generated by protoc-gen-go-resource. DO NOT EDIT.
// source: reference/reference.proto

package reference

import (
	fmt "fmt"
	external "github.com/protoc-contrib/protoc-gen-go-resource/internal/generator/testpb/external"
	simple "github.com/protoc-contrib/protoc-gen-go-resource/internal/generator/testpb/simple"
	strings "strings"
)

type ParsedFooName struct {
	FooID string
}

func ParseFooName(s string) (ParsedFooName, error) {
	parts := strings.Split(s, "/")
	if len(parts) != 2 {
		return ParsedFooName{}, fmt.Errorf("parse %q: bad number of segments, want: 2, got: %d", s, len(parts))
	}
	var out ParsedFooName
	if parts[0] != "foos" {
		return ParsedFooName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "foos", parts[0])
	}
	out.FooID = parts[1]
	return out, nil
}

func ParseFullFooName(s string) (ParsedFooName, error) {
	if !strings.HasPrefix(s, "//example.com/") {
		return ParsedFooName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//example.com/")
	}
	return ParseFooName(strings.TrimPrefix(s, "//example.com/"))
}

func (n ParsedFooName) Name() string {
	return "foos/" + n.FooID
}

func (n ParsedFooName) FullName() string {
	return "//example.com/" + n.Name()
}

type ParsedBarName struct {
	BarID string
}

func ParseBarName(s string) (ParsedBarName, error) {
	parts := strings.Split(s, "/")
	if len(parts) != 2 {
		return ParsedBarName{}, fmt.Errorf("parse %q: bad number of segments, want: 2, got: %d", s, len(parts))
	}
	var out ParsedBarName
	if parts[0] != "bars" {
		return ParsedBarName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "bars", parts[0])
	}
	out.BarID = parts[1]
	return out, nil
}

func ParseFullBarName(s string) (ParsedBarName, error) {
	if !strings.HasPrefix(s, "//example.com/") {
		return ParsedBarName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//example.com/")
	}
	return ParseBarName(strings.TrimPrefix(s, "//example.com/"))
}

func (n ParsedBarName) Name() string {
	return "bars/" + n.BarID
}

func (n ParsedBarName) FullName() string {
	return "//example.com/" + n.Name()
}

func (x *Foo) ParseName() (ParsedFooName, error) {
	return ParseFooName(x.Name)
}

func (x *Foo) ParseBar() (ParsedBarName, error) {
	return ParseBarName(x.Bar)
}

func (x *Bar) ParseName() (ParsedBarName, error) {
	return ParseBarName(x.Name)
}

func (x *Bar) ParseFoo() (ParsedFooName, error) {
	return ParseFooName(x.Foo)
}

func (x *CrossPackage) ParseThingName() (simple.ParsedThingName, error) {
	return simple.ParseThingName(x.ThingName)
}

func (x *CrossPackageExternal) ParseExternalName() (external.ParsedExternalName, error) {
	return external.ParseExternalName(x.ExternalName)
}
