// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: reference/reference.proto

package reference

import (
	_ "github.com/protoc-contrib/protoc-gen-go-resource/internal/generator/testpb/external"
	_ "github.com/protoc-contrib/protoc-gen-go-resource/internal/generator/testpb/simple"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Foo and Bar cross-reference each other; ParseBar on Foo and ParseFoo on
// Bar should resolve to the parsers of the referent resource.
type Foo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Bar           string                 `protobuf:"bytes,2,opt,name=bar,proto3" json:"bar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Foo) Reset() {
	*x = Foo{}
	mi := &file_reference_reference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Foo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Foo) ProtoMessage() {}

func (x *Foo) ProtoReflect() protoreflect.Message {
	mi := &file_reference_reference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Foo.ProtoReflect.Descriptor instead.
func (*Foo) Descriptor() ([]byte, []int) {
	return file_reference_reference_proto_rawDescGZIP(), []int{0}
}

func (x *Foo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Foo) GetBar() string {
	if x != nil {
		return x.Bar
	}
	return ""
}

type Bar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Foo           string                 `protobuf:"bytes,2,opt,name=foo,proto3" json:"foo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bar) Reset() {
	*x = Bar{}
	mi := &file_reference_reference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bar) ProtoMessage() {}

func (x *Bar) ProtoReflect() protoreflect.Message {
	mi := &file_reference_reference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bar.ProtoReflect.Descriptor instead.
func (*Bar) Descriptor() ([]byte, []int) {
	return file_reference_reference_proto_rawDescGZIP(), []int{1}
}

func (x *Bar) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bar) GetFoo() string {
	if x != nil {
		return x.Foo
	}
	return ""
}

// CrossPackage references a message-level resource defined in another proto
// package.
type CrossPackage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThingName     string                 `protobuf:"bytes,1,opt,name=thing_name,json=thingName,proto3" json:"thing_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrossPackage) Reset() {
	*x = CrossPackage{}
	mi := &file_reference_reference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrossPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossPackage) ProtoMessage() {}

func (x *CrossPackage) ProtoReflect() protoreflect.Message {
	mi := &file_reference_reference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossPackage.ProtoReflect.Descriptor instead.
func (*CrossPackage) Descriptor() ([]byte, []int) {
	return file_reference_reference_proto_rawDescGZIP(), []int{2}
}

func (x *CrossPackage) GetThingName() string {
	if x != nil {
		return x.ThingName
	}
	return ""
}

// CrossPackageExternal references a resource declared at file scope in
// another package (google.api.resource_definition).
type CrossPackageExternal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalName  string                 `protobuf:"bytes,1,opt,name=external_name,json=externalName,proto3" json:"external_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrossPackageExternal) Reset() {
	*x = CrossPackageExternal{}
	mi := &file_reference_reference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrossPackageExternal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossPackageExternal) ProtoMessage() {}

func (x *CrossPackageExternal) ProtoReflect() protoreflect.Message {
	mi := &file_reference_reference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossPackageExternal.ProtoReflect.Descriptor instead.
func (*CrossPackageExternal) Descriptor() ([]byte, []int) {
	return file_reference_reference_proto_rawDescGZIP(), []int{3}
}

func (x *CrossPackageExternal) GetExternalName() string {
	if x != nil {
		return x.ExternalName
	}
	return ""
}

// child_type references are not supported by the generator — without a
// pattern on the referring field we can't emit a parser. The field is
// retained here to verify the generator silently skips it.
type ChildTypeIgnored struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChildTypeIgnored) Reset() {
	*x = ChildTypeIgnored{}
	mi := &file_reference_reference_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChildTypeIgnored) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChildTypeIgnored) ProtoMessage() {}

func (x *ChildTypeIgnored) ProtoReflect() protoreflect.Message {
	mi := &file_reference_reference_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChildTypeIgnored.ProtoReflect.Descriptor instead.
func (*ChildTypeIgnored) Descriptor() ([]byte, []int) {
	return file_reference_reference_proto_rawDescGZIP(), []int{4}
}

func (x *ChildTypeIgnored) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

// Wildcard references are not bound to a specific type — also silently
// skipped.
type WildcardReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Something     string                 `protobuf:"bytes,1,opt,name=something,proto3" json:"something,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WildcardReference) Reset() {
	*x = WildcardReference{}
	mi := &file_reference_reference_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WildcardReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WildcardReference) ProtoMessage() {}

func (x *WildcardReference) ProtoReflect() protoreflect.Message {
	mi := &file_reference_reference_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WildcardReference.ProtoReflect.Descriptor instead.
func (*WildcardReference) Descriptor() ([]byte, []int) {
	return file_reference_reference_proto_rawDescGZIP(), []int{5}
}

func (x *WildcardReference) GetSomething() string {
	if x != nil {
		return x.Something
	}
	return ""
}

var File_reference_reference_proto protoreflect.FileDescriptor

const file_reference_reference_proto_rawDesc = "" +
	"\n" +
	"\x19reference/reference.proto\x12\x0ftests.reference\x1a\x19google/api/resource.proto\x1a\x17external/external.proto\x1a\x13simple/simple.proto\"c\n" +
	"\x03Foo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x03bar\x18\x02 \x01(\tB\x14\xfaA\x11\n" +
	"\x0fexample.com/BarR\x03bar: \xeaA\x1d\n" +
	"\x0fexample.com/Foo\x12\n" +
	"foos/{foo}\"c\n" +
	"\x03Bar\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x03foo\x18\x02 \x01(\tB\x14\xfaA\x11\n" +
	"\x0fexample.com/FooR\x03foo: \xeaA\x1d\n" +
	"\x0fexample.com/Bar\x12\n" +
	"bars/{bar}\"E\n" +
	"\fCrossPackage\x125\n" +
	"\n" +
	"thing_name\x18\x01 \x01(\tB\x16\xfaA\x13\n" +
	"\x11example.com/ThingR\tthingName\"V\n" +
	"\x14CrossPackageExternal\x12>\n" +
	"\rexternal_name\x18\x01 \x01(\tB\x19\xfaA\x16\n" +
	"\x14example.com/ExternalR\fexternalName\"@\n" +
	"\x10ChildTypeIgnored\x12,\n" +
	"\x06parent\x18\x01 \x01(\tB\x14\xfaA\x11\x12\x0fexample.com/FooR\x06parent\"9\n" +
	"\x11WildcardReference\x12$\n" +
	"\tsomething\x18\x01 \x01(\tB\x06\xfaA\x03\n" +
	"\x01*R\tsomethingBVZTgithub.com/protoc-contrib/protoc-gen-go-resource/internal/generator/testpb/referenceb\x06proto3"

var (
	file_reference_reference_proto_rawDescOnce sync.Once
	file_reference_reference_proto_rawDescData []byte
)

func file_reference_reference_proto_rawDescGZIP() []byte {
	file_reference_reference_proto_rawDescOnce.Do(func() {
		file_reference_reference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reference_reference_proto_rawDesc), len(file_reference_reference_proto_rawDesc)))
	})
	return file_reference_reference_proto_rawDescData
}

var file_reference_reference_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_reference_reference_proto_goTypes = []any{
	(*Foo)(nil),                  // 0: tests.reference.Foo
	(*Bar)(nil),                  // 1: tests.reference.Bar
	(*CrossPackage)(nil),         // 2: tests.reference.CrossPackage
	(*CrossPackageExternal)(nil), // 3: tests.reference.CrossPackageExternal
	(*ChildTypeIgnored)(nil),     // 4: tests.reference.ChildTypeIgnored
	(*WildcardReference)(nil),    // 5: tests.reference.WildcardReference
}
var file_reference_reference_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_reference_reference_proto_init() }
func file_reference_reference_proto_init() {
	if File_reference_reference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reference_reference_proto_rawDesc), len(file_reference_reference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_reference_reference_proto_goTypes,
		DependencyIndexes: file_reference_reference_proto_depIdxs,
		MessageInfos:      file_reference_reference_proto_msgTypes,
	}.Build()
	File_reference_reference_proto = out.File
	file_reference_reference_proto_goTypes = nil
	file_reference_reference_proto_depIdxs = nil
}
