// Code generated by protoc-gen-go-resource. DO NOT EDIT.
// source: uuid/uuid.proto

package uuid

import (
	fmt "fmt"
	uuid "github.com/google/uuid"
	strings "strings"
)

// CollectionName is the parsed form of a "example.com/Collection" resource name (pattern "collections/{collection}").
type CollectionName struct {
	CollectionID uuid.UUID
}

// ParseCollectionName parses s as CollectionName (pattern "collections/{collection}").
func ParseCollectionName(s string) (CollectionName, error) {
	parts := strings.Split(s, "/")
	if len(parts) != 2 {
		return CollectionName{}, fmt.Errorf("parse %q: bad number of segments, want: 2, got: %d", s, len(parts))
	}
	var out CollectionName
	if parts[0] != "collections" {
		return CollectionName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "collections", parts[0])
	}
	if parts[1] == "" {
		return CollectionName{}, fmt.Errorf("parse %q: empty value for segment 1", s)
	}
	v1, err := uuid.Parse(parts[1])
	if err != nil {
		return CollectionName{}, fmt.Errorf("parse %q: segment 1: %w", s, err)
	}
	out.CollectionID = v1
	return out, nil
}

// ParseFullCollectionName parses s as the fully-qualified form of CollectionName (prefix "//example.com/").
func ParseFullCollectionName(s string) (CollectionName, error) {
	if !strings.HasPrefix(s, "//example.com/") {
		return CollectionName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//example.com/")
	}
	return ParseCollectionName(strings.TrimPrefix(s, "//example.com/"))
}

// String returns the relative resource name "collections/{collection}" and implements fmt.Stringer.
func (n CollectionName) String() string {
	return "collections/" + n.CollectionID.String()
}

// FullName returns the fully-qualified resource name prefixed with "//example.com/".
func (n CollectionName) FullName() string {
	return "//example.com/" + n.String()
}

// MarshalText implements encoding.TextMarshaler and emits the relative resource name.
func (n CollectionName) MarshalText() ([]byte, error) {
	return []byte(n.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler by parsing b as a relative CollectionName.
func (n *CollectionName) UnmarshalText(b []byte) error {
	parsed, err := ParseCollectionName(string(b))
	if err != nil {
		return err
	}
	*n = parsed
	return nil
}

// FormatCollectionName returns the relative resource name for a "example.com/Collection" with the given id.
func FormatCollectionName(id uuid.UUID) string {
	return CollectionName{CollectionID: id}.String()
}

// ParseCollectionID parses s as CollectionName and returns its CollectionID field.
func ParseCollectionID(s string) (uuid.UUID, error) {
	parsed, err := ParseCollectionName(s)
	return parsed.CollectionID, err
}

// OrganizationName is the parsed form of a "example.com/Organization" resource name (pattern "organizations/{organization}").
type OrganizationName struct {
	OrganizationID uuid.UUID
}

// ParseOrganizationName parses s as OrganizationName (pattern "organizations/{organization}").
func ParseOrganizationName(s string) (OrganizationName, error) {
	parts := strings.Split(s, "/")
	if len(parts) != 2 {
		return OrganizationName{}, fmt.Errorf("parse %q: bad number of segments, want: 2, got: %d", s, len(parts))
	}
	var out OrganizationName
	if parts[0] != "organizations" {
		return OrganizationName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "organizations", parts[0])
	}
	if parts[1] == "" {
		return OrganizationName{}, fmt.Errorf("parse %q: empty value for segment 1", s)
	}
	v1, err := uuid.Parse(parts[1])
	if err != nil {
		return OrganizationName{}, fmt.Errorf("parse %q: segment 1: %w", s, err)
	}
	out.OrganizationID = v1
	return out, nil
}

// ParseFullOrganizationName parses s as the fully-qualified form of OrganizationName (prefix "//example.com/").
func ParseFullOrganizationName(s string) (OrganizationName, error) {
	if !strings.HasPrefix(s, "//example.com/") {
		return OrganizationName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//example.com/")
	}
	return ParseOrganizationName(strings.TrimPrefix(s, "//example.com/"))
}

// String returns the relative resource name "organizations/{organization}" and implements fmt.Stringer.
func (n OrganizationName) String() string {
	return "organizations/" + n.OrganizationID.String()
}

// FullName returns the fully-qualified resource name prefixed with "//example.com/".
func (n OrganizationName) FullName() string {
	return "//example.com/" + n.String()
}

// MarshalText implements encoding.TextMarshaler and emits the relative resource name.
func (n OrganizationName) MarshalText() ([]byte, error) {
	return []byte(n.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler by parsing b as a relative OrganizationName.
func (n *OrganizationName) UnmarshalText(b []byte) error {
	parsed, err := ParseOrganizationName(string(b))
	if err != nil {
		return err
	}
	*n = parsed
	return nil
}

// FormatOrganizationName returns the relative resource name for a "example.com/Organization" with the given id.
func FormatOrganizationName(id uuid.UUID) string {
	return OrganizationName{OrganizationID: id}.String()
}

// ParseOrganizationID parses s as OrganizationName and returns its OrganizationID field.
func ParseOrganizationID(s string) (uuid.UUID, error) {
	parsed, err := ParseOrganizationName(s)
	return parsed.OrganizationID, err
}

// ItemName is the parsed form of a "example.com/Item" resource name (pattern "organizations/{organization}/items/{item}").
type ItemName struct {
	OrganizationID uuid.UUID
	ItemID         uuid.UUID
}

// ParseItemName parses s as ItemName (pattern "organizations/{organization}/items/{item}").
func ParseItemName(s string) (ItemName, error) {
	parts := strings.Split(s, "/")
	if len(parts) != 4 {
		return ItemName{}, fmt.Errorf("parse %q: bad number of segments, want: 4, got: %d", s, len(parts))
	}
	var out ItemName
	if parts[0] != "organizations" {
		return ItemName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "organizations", parts[0])
	}
	if parts[1] == "" {
		return ItemName{}, fmt.Errorf("parse %q: empty value for segment 1", s)
	}
	v1, err := uuid.Parse(parts[1])
	if err != nil {
		return ItemName{}, fmt.Errorf("parse %q: segment 1: %w", s, err)
	}
	out.OrganizationID = v1
	if parts[2] != "items" {
		return ItemName{}, fmt.Errorf("parse %q: bad segment 2, want: %q, got: %q", s, "items", parts[2])
	}
	if parts[3] == "" {
		return ItemName{}, fmt.Errorf("parse %q: empty value for segment 3", s)
	}
	v3, err := uuid.Parse(parts[3])
	if err != nil {
		return ItemName{}, fmt.Errorf("parse %q: segment 3: %w", s, err)
	}
	out.ItemID = v3
	return out, nil
}

// ParseFullItemName parses s as the fully-qualified form of ItemName (prefix "//example.com/").
func ParseFullItemName(s string) (ItemName, error) {
	if !strings.HasPrefix(s, "//example.com/") {
		return ItemName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//example.com/")
	}
	return ParseItemName(strings.TrimPrefix(s, "//example.com/"))
}

// String returns the relative resource name "organizations/{organization}/items/{item}" and implements fmt.Stringer.
func (n ItemName) String() string {
	return "organizations/" + n.OrganizationID.String() + "/items/" + n.ItemID.String()
}

// FullName returns the fully-qualified resource name prefixed with "//example.com/".
func (n ItemName) FullName() string {
	return "//example.com/" + n.String()
}

// MarshalText implements encoding.TextMarshaler and emits the relative resource name.
func (n ItemName) MarshalText() ([]byte, error) {
	return []byte(n.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler by parsing b as a relative ItemName.
func (n *ItemName) UnmarshalText(b []byte) error {
	parsed, err := ParseItemName(string(b))
	if err != nil {
		return err
	}
	*n = parsed
	return nil
}

// Parent returns the parent OrganizationName derived from this resource's fields.
func (n ItemName) Parent() OrganizationName {
	return OrganizationName{
		OrganizationID: n.OrganizationID,
	}
}

// ParseName parses x.Name as CollectionName.
func (x *Collection) ParseName() (CollectionName, error) {
	return ParseCollectionName(x.Name)
}

// ParseFullName parses x.Name as CollectionName.
func (x *Collection) ParseFullName() (CollectionName, error) {
	return ParseFullCollectionName(x.Name)
}

// ParseName parses x.Name as OrganizationName.
func (x *Organization) ParseName() (OrganizationName, error) {
	return ParseOrganizationName(x.Name)
}

// ParseFullName parses x.Name as OrganizationName.
func (x *Organization) ParseFullName() (OrganizationName, error) {
	return ParseFullOrganizationName(x.Name)
}

// ParseName parses x.Name as ItemName.
func (x *Item) ParseName() (ItemName, error) {
	return ParseItemName(x.Name)
}

// ParseFullName parses x.Name as ItemName.
func (x *Item) ParseFullName() (ItemName, error) {
	return ParseFullItemName(x.Name)
}
