// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: namefield/namefield.proto

package namefield

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Person exercises a resource whose name lives in a field other than "name".
type Person struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PersonName    string                 `protobuf:"bytes,1,opt,name=person_name,json=personName,proto3" json:"person_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Person) Reset() {
	*x = Person{}
	mi := &file_namefield_namefield_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_namefield_namefield_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_namefield_namefield_proto_rawDescGZIP(), []int{0}
}

func (x *Person) GetPersonName() string {
	if x != nil {
		return x.PersonName
	}
	return ""
}

var File_namefield_namefield_proto protoreflect.FileDescriptor

const file_namefield_namefield_proto_rawDesc = "" +
	"\n" +
	"\x19namefield/namefield.proto\x12\x0ftests.namefield\x1a\x19google/api/resource.proto\"a\n" +
	"\x06Person\x12\x1f\n" +
	"\vperson_name\x18\x01 \x01(\tR\n" +
	"personName:6\xeaA3\n" +
	"\x12example.com/Person\x12\x10persons/{person}\x1a\vperson_nameBVZTgithub.com/protoc-contrib/protoc-gen-go-resource/internal/generator/testpb/namefieldb\x06proto3"

var (
	file_namefield_namefield_proto_rawDescOnce sync.Once
	file_namefield_namefield_proto_rawDescData []byte
)

func file_namefield_namefield_proto_rawDescGZIP() []byte {
	file_namefield_namefield_proto_rawDescOnce.Do(func() {
		file_namefield_namefield_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_namefield_namefield_proto_rawDesc), len(file_namefield_namefield_proto_rawDesc)))
	})
	return file_namefield_namefield_proto_rawDescData
}

var file_namefield_namefield_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_namefield_namefield_proto_goTypes = []any{
	(*Person)(nil), // 0: tests.namefield.Person
}
var file_namefield_namefield_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_namefield_namefield_proto_init() }
func file_namefield_namefield_proto_init() {
	if File_namefield_namefield_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_namefield_namefield_proto_rawDesc), len(file_namefield_namefield_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_namefield_namefield_proto_goTypes,
		DependencyIndexes: file_namefield_namefield_proto_depIdxs,
		MessageInfos:      file_namefield_namefield_proto_msgTypes,
	}.Build()
	File_namefield_namefield_proto = out.File
	file_namefield_namefield_proto_goTypes = nil
	file_namefield_namefield_proto_depIdxs = nil
}
