// Code generated by protoc-gen-go-resource. DO NOT EDIT.
// source: namefield/namefield.proto

package namefield

import (
	fmt "fmt"
	strings "strings"
)

type PersonName struct {
	PersonID string
}

func ParsePersonName(s string) (PersonName, error) {
	parts := strings.Split(s, "/")
	if len(parts) != 2 {
		return PersonName{}, fmt.Errorf("parse %q: bad number of segments, want: 2, got: %d", s, len(parts))
	}
	var out PersonName
	if parts[0] != "persons" {
		return PersonName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "persons", parts[0])
	}
	if parts[1] == "" {
		return PersonName{}, fmt.Errorf("parse %q: empty value for segment 1", s)
	}
	out.PersonID = parts[1]
	return out, nil
}

func ParseFullPersonName(s string) (PersonName, error) {
	if !strings.HasPrefix(s, "//example.com/") {
		return PersonName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//example.com/")
	}
	return ParsePersonName(strings.TrimPrefix(s, "//example.com/"))
}

func (n PersonName) Name() string {
	return "persons/" + n.PersonID
}

func (n PersonName) FullName() string {
	return "//example.com/" + n.Name()
}

func (x *Person) ParsePersonName() (PersonName, error) {
	return ParsePersonName(x.PersonName)
}

func (x *Person) ParseFullPersonName() (PersonName, error) {
	return ParseFullPersonName(x.PersonName)
}
