// Code generated by protoc-gen-go-resource. DO NOT EDIT.
// source: namefield/namefield.proto

package namefield

import (
	fmt "fmt"
	strings "strings"
)

// PersonName is the parsed form of a "example.com/Person" resource name (pattern "persons/{person}").
type PersonName struct {
	PersonID string
}

// ParsePersonName parses s as PersonName (pattern "persons/{person}").
func ParsePersonName(s string) (PersonName, error) {
	parts := strings.Split(s, "/")
	if len(parts) != 2 {
		return PersonName{}, fmt.Errorf("parse %q: bad number of segments, want: 2, got: %d", s, len(parts))
	}
	var out PersonName
	if parts[0] != "persons" {
		return PersonName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "persons", parts[0])
	}
	if parts[1] == "" {
		return PersonName{}, fmt.Errorf("parse %q: empty value for segment 1", s)
	}
	out.PersonID = parts[1]
	return out, nil
}

// ParseFullPersonName parses s as the fully-qualified form of PersonName (prefix "//example.com/").
func ParseFullPersonName(s string) (PersonName, error) {
	if !strings.HasPrefix(s, "//example.com/") {
		return PersonName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//example.com/")
	}
	return ParsePersonName(strings.TrimPrefix(s, "//example.com/"))
}

// String returns the relative resource name "persons/{person}" and implements fmt.Stringer.
func (n PersonName) String() string {
	return "persons/" + n.PersonID
}

// FullName returns the fully-qualified resource name prefixed with "//example.com/".
func (n PersonName) FullName() string {
	return "//example.com/" + n.String()
}

// MarshalText implements encoding.TextMarshaler and emits the relative resource name.
func (n PersonName) MarshalText() ([]byte, error) {
	return []byte(n.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler by parsing b as a relative PersonName.
func (n *PersonName) UnmarshalText(b []byte) error {
	parsed, err := ParsePersonName(string(b))
	if err != nil {
		return err
	}
	*n = parsed
	return nil
}

// ParsePersonName parses x.PersonName as PersonName.
func (x *Person) ParsePersonName() (PersonName, error) {
	return ParsePersonName(x.PersonName)
}

// ParseFullPersonName parses x.PersonName as PersonName.
func (x *Person) ParseFullPersonName() (PersonName, error) {
	return ParseFullPersonName(x.PersonName)
}
