// Code generated by protoc-gen-go-resource. DO NOT EDIT.
// source: namefield/namefield.proto

package namefield

import (
	fmt "fmt"
	strings "strings"
)

type ParsedPersonName struct {
	PersonID string
}

func ParsePersonName(s string) (ParsedPersonName, error) {
	parts := strings.Split(s, "/")
	if len(parts) != 2 {
		return ParsedPersonName{}, fmt.Errorf("parse %q: bad number of segments, want: 2, got: %d", s, len(parts))
	}
	var out ParsedPersonName
	if parts[0] != "persons" {
		return ParsedPersonName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "persons", parts[0])
	}
	out.PersonID = parts[1]
	return out, nil
}

func ParseFullPersonName(s string) (ParsedPersonName, error) {
	if !strings.HasPrefix(s, "//example.com/") {
		return ParsedPersonName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//example.com/")
	}
	return ParsePersonName(strings.TrimPrefix(s, "//example.com/"))
}

func (n ParsedPersonName) Name() string {
	return "persons/" + n.PersonID
}

func (n ParsedPersonName) FullName() string {
	return "//example.com/" + n.Name()
}

func (x *Person) ParsePersonName() (ParsedPersonName, error) {
	return ParsePersonName(x.PersonName)
}
