// Package generator emits Go helpers for parsing and reconstructing
// Google API resource names declared via google.api.resource and
// google.api.resource_reference annotations.
package generator

import (
	"fmt"
	"strconv"

	"google.golang.org/genproto/googleapis/api/annotations"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
)

const (
	generatedFilenameSuffix = ".pb.resource.go"

	fmtPackage     = protogen.GoImportPath("fmt")
	stringsPackage = protogen.GoImportPath("strings")
)

// Generate walks every proto file in the plugin request, builds a registry of
// resource definitions across all files (so cross-file references resolve),
// and emits a *.pb.resource.go companion for every file scheduled for
// generation that actually contains a resource or a resource reference.
//
// The error return is currently reserved: validation errors surface through
// panicking protogen routines and newMessageResource.
func Generate(plugin *protogen.Plugin, opts *Options) error {
	if opts == nil {
		opts = &Options{}
	}

	reg := newRegistry()
	for _, f := range plugin.Files {
		if err := reg.walkFile(f); err != nil {
			return err
		}
	}

	for _, f := range plugin.Files {
		if !f.Generate {
			continue
		}
		if err := generateFile(plugin, f, reg); err != nil {
			return err
		}
	}
	return nil
}

// registry indexes every resource definition discovered during the walk,
// keyed both by proto file (for iteration order) and by resource type (so
// google.api.resource_reference fields can resolve to their referent across
// package boundaries).
type registry struct {
	byFile map[*protogen.File][]*resource
	byType map[resourceType]*resource
}

func newRegistry() *registry {
	return &registry{
		byFile: map[*protogen.File][]*resource{},
		byType: map[resourceType]*resource{},
	}
}

func (r *registry) insert(f *protogen.File, res *resource) {
	r.byFile[f] = append(r.byFile[f], res)
	r.byType[res.Type] = res
}

func (r *registry) walkFile(f *protogen.File) error {
	fileResources, err := newFileResources(f)
	if err != nil {
		return fmt.Errorf("%s: file-level resources: %w", f.Desc.Path(), err)
	}
	for _, res := range fileResources {
		r.insert(f, res)
	}

	var walk func(msgs []*protogen.Message) error
	walk = func(msgs []*protogen.Message) error {
		for _, m := range msgs {
			res, err := newMessageResource(m)
			if err != nil {
				return fmt.Errorf("%v: %w", m.GoIdent, err)
			}
			if res != nil {
				r.insert(f, res)
			}
			if err := walk(m.Messages); err != nil {
				return err
			}
		}
		return nil
	}
	return walk(f.Messages)
}

func generateFile(plugin *protogen.Plugin, f *protogen.File, reg *registry) error {
	resources := reg.byFile[f]
	refs, err := collectReferences(f, reg)
	if err != nil {
		return err
	}
	if len(resources) == 0 && len(refs) == 0 {
		return nil
	}

	g := plugin.NewGeneratedFile(f.GeneratedFilenamePrefix+generatedFilenameSuffix, f.GoImportPath)
	g.P("// Code generated by protoc-gen-go-resource. DO NOT EDIT.")
	g.P("// source: ", f.Desc.Path())
	g.P()
	g.P("package ", f.GoPackageName)
	g.P()

	for _, res := range resources {
		emitResource(g, res)
	}
	for _, ref := range refs {
		emitReference(g, ref)
	}
	return nil
}

// emitResource emits the parse/reconstruct helpers for a single resource.
// Single-pattern resources produce a struct; multi-pattern resources produce
// one struct per pattern plus a sealed interface and a polymorphic parser.
func emitResource(g *protogen.GeneratedFile, r *resource) {
	if len(r.Patterns) == 1 {
		emitSinglePattern(g, r, r.ParsedType.GoName, r.ParseFunc.GoName, r.FullParseFunc.GoName, "", r.Patterns[0])
		return
	}

	embed := "mustEmbed" + r.ParsedType.GoName
	implNames := make([]string, len(r.Patterns))
	for i, p := range r.Patterns {
		typeName := r.ParsedType.GoName + "_" + strconv.Itoa(i)
		funcName := r.ParseFunc.GoName + "_" + strconv.Itoa(i)
		fullFuncName := r.ParseFunc.GoName + "Full_" + strconv.Itoa(i)
		emitSinglePattern(g, r, typeName, funcName, fullFuncName, embed, p)
		implNames[i] = funcName
	}
	emitMultiPatternInterface(g, r, embed, implNames)
}

// emitSinglePattern emits a struct, its Parse/ParseFull functions, and the
// Name/FullName methods. When embedFunc is non-empty, a sealed interface
// marker method is also emitted so the struct can satisfy the multi-pattern
// interface.
func emitSinglePattern(g *protogen.GeneratedFile, r *resource, typeName, funcName, fullFuncName, embedFunc string, p pattern) {
	prefix := r.servicePrefix()

	g.P("type ", typeName, " struct {")
	for _, s := range p {
		if s.Var {
			g.P(s.FieldName(), " string")
		}
	}
	g.P("}")
	g.P()

	g.P("func ", funcName, "(s string) (", typeName, ", error) {")
	g.P("parts := ", stringsPackage.Ident("Split"), "(s, \"/\")")
	g.P("if len(parts) != ", len(p), " {")
	g.P("return ", typeName, "{}, ", fmtPackage.Ident("Errorf"), "(\"parse %q: bad number of segments, want: ", len(p), ", got: %d\", s, len(parts))")
	g.P("}")
	g.P("var out ", typeName)
	for i, s := range p {
		if s.Var {
			g.P("out.", s.FieldName(), " = parts[", i, "]")
			continue
		}
		g.P("if parts[", i, "] != ", strconv.Quote(s.Name), " {")
		g.P("return ", typeName, "{}, ", fmtPackage.Ident("Errorf"), "(\"parse %q: bad segment ", i, ", want: %q, got: %q\", s, ", strconv.Quote(s.Name), ", parts[", i, "])")
		g.P("}")
	}
	g.P("return out, nil")
	g.P("}")
	g.P()

	g.P("func ", fullFuncName, "(s string) (", typeName, ", error) {")
	g.P("if !", stringsPackage.Ident("HasPrefix"), "(s, ", strconv.Quote(prefix), ") {")
	g.P("return ", typeName, "{}, ", fmtPackage.Ident("Errorf"), "(\"parse %q: invalid prefix, want: %q\", s, ", strconv.Quote(prefix), ")")
	g.P("}")
	g.P("return ", funcName, "(", stringsPackage.Ident("TrimPrefix"), "(s, ", strconv.Quote(prefix), "))")
	g.P("}")
	g.P()

	g.P("func (n ", typeName, ") Name() string {")
	g.P("return ", nameExpression(p))
	g.P("}")
	g.P()

	g.P("func (n ", typeName, ") FullName() string {")
	g.P("return ", strconv.Quote(prefix), " + n.Name()")
	g.P("}")
	g.P()

	if embedFunc != "" {
		g.P("func (n ", typeName, ") ", embedFunc, "() {}")
		g.P()
	}
}

// nameExpression builds the string-concatenation expression used in Name().
// For "projects/{project}/books/{book}" it yields: "projects/" + n.ProjectID + "/books/" + n.BookID
func nameExpression(p pattern) string {
	var parts []string
	var literal string
	flushLiteral := func() {
		if literal != "" {
			parts = append(parts, strconv.Quote(literal))
			literal = ""
		}
	}
	for i, s := range p {
		if i > 0 {
			literal += "/"
		}
		if s.Var {
			flushLiteral()
			parts = append(parts, "n."+s.FieldName())
			continue
		}
		literal += s.Name
	}
	flushLiteral()

	var expr string
	for i, part := range parts {
		if i > 0 {
			expr += " + "
		}
		expr += part
	}
	return expr
}

func emitMultiPatternInterface(g *protogen.GeneratedFile, r *resource, embed string, implNames []string) {
	prefix := r.servicePrefix()

	g.P("type ", r.ParsedType.GoName, " interface {")
	g.P("Name() string")
	g.P("FullName() string")
	g.P(embed, "()")
	g.P("}")
	g.P()

	g.P("func ", r.ParseFunc.GoName, "(s string) (", r.ParsedType.GoName, ", error) {")
	g.P("var errs []string")
	for i, name := range implNames {
		g.P("if res, err := ", name, "(s); err == nil {")
		g.P("return res, nil")
		g.P("} else {")
		g.P("errs = append(errs, ", fmtPackage.Ident("Sprintf"), "(\"pattern ", i, ": %v\", err))")
		g.P("}")
	}
	g.P("return nil, ", fmtPackage.Ident("Errorf"), "(\"no pattern matches input: %v\", ", stringsPackage.Ident("Join"), "(errs, \"; \"))")
	g.P("}")
	g.P()

	g.P("func ", r.FullParseFunc.GoName, "(s string) (", r.ParsedType.GoName, ", error) {")
	g.P("if !", stringsPackage.Ident("HasPrefix"), "(s, ", strconv.Quote(prefix), ") {")
	g.P("return nil, ", fmtPackage.Ident("Errorf"), "(\"parse %q: invalid prefix, want: %q\", s, ", strconv.Quote(prefix), ")")
	g.P("}")
	g.P("return ", r.ParseFunc.GoName, "(", stringsPackage.Ident("TrimPrefix"), "(s, ", strconv.Quote(prefix), "))")
	g.P("}")
	g.P()
}

// reference is a message field that carries a resource name the generator can
// parse — either the message's own name field (from google.api.resource) or
// any field carrying google.api.resource_reference.
type reference struct {
	Owner     *protogen.Message
	FieldName string           // Go name of the field whose value should be parsed
	MethodTag string           // suffix appended to "Parse" to form the method name
	Referent  *resource        // the resource whose parser we delegate to
	Qualifier protogen.GoIdent // the referent's ParseFunc ident, for cross-package refs
}

// collectReferences walks every message in the file and returns the parse
// helper methods to emit on that message.
func collectReferences(f *protogen.File, reg *registry) ([]reference, error) {
	var out []reference
	var walk func(msgs []*protogen.Message) error
	walk = func(msgs []*protogen.Message) error {
		for _, m := range msgs {
			res, err := newMessageResource(m)
			if err != nil {
				return err
			}
			if res != nil {
				out = append(out, reference{
					Owner:     m,
					FieldName: res.NameField.GoName,
					MethodTag: res.NameField.GoName,
					Referent:  res,
					Qualifier: res.ParseFunc,
				})
			}
			for _, field := range m.Fields {
				ref, ok, err := fieldReference(m, field, reg)
				if err != nil {
					return err
				}
				if ok {
					out = append(out, ref)
				}
			}
			if err := walk(m.Messages); err != nil {
				return err
			}
		}
		return nil
	}
	if err := walk(f.Messages); err != nil {
		return nil, err
	}
	return out, nil
}

func fieldReference(m *protogen.Message, field *protogen.Field, reg *registry) (reference, bool, error) {
	opts, _ := field.Desc.Options().(*descriptorpb.FieldOptions)
	rr, _ := proto.GetExtension(opts, annotations.E_ResourceReference).(*annotations.ResourceReference)
	if rr == nil {
		return reference{}, false, nil
	}
	// Ignore fields that don't set "type", or set it to the wildcard. Also
	// ignore child_type references — the generator can't know what pattern to
	// use for a child without extra context.
	if rr.Type == "" || rr.Type == "*" {
		return reference{}, false, nil
	}
	rt, err := newResourceType(rr.Type)
	if err != nil {
		return reference{}, false, fmt.Errorf("%v: resource reference: %w", field.GoIdent, err)
	}
	res, ok := reg.byType[rt]
	if !ok {
		return reference{}, false, fmt.Errorf("%v: reference to unknown type %q", field.GoIdent, rr.Type)
	}
	return reference{
		Owner:     m,
		FieldName: field.GoName,
		MethodTag: field.GoName,
		Referent:  res,
		Qualifier: res.ParseFunc,
	}, true, nil
}

func emitReference(g *protogen.GeneratedFile, ref reference) {
	g.P("func (x *", ref.Owner.GoIdent, ") Parse", ref.MethodTag, "() (", ref.Referent.ParsedType, ", error) {")
	g.P("return ", ref.Qualifier, "(x.", ref.FieldName, ")")
	g.P("}")
	g.P()
}
