package generator_test

import (
	"os"
	"path/filepath"
	"strings"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protodesc"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/pluginpb"

	"github.com/protoc-contrib/protoc-gen-go-resource/internal/generator"
	externalpb "github.com/protoc-contrib/protoc-gen-go-resource/internal/generator/testpb/external"
	multipb "github.com/protoc-contrib/protoc-gen-go-resource/internal/generator/testpb/multipattern"
	namefieldpb "github.com/protoc-contrib/protoc-gen-go-resource/internal/generator/testpb/namefield"
	refpb "github.com/protoc-contrib/protoc-gen-go-resource/internal/generator/testpb/reference"
	simplepb "github.com/protoc-contrib/protoc-gen-go-resource/internal/generator/testpb/simple"
)

// runGenerator builds a CodeGeneratorRequest covering the given file
// descriptors (plus their transitive imports) and runs Generate against it.
// The files passed in are the ones flagged for generation; transitive
// imports are registered with the plugin but not emitted.
func runGenerator(opts *generator.Options, files ...protoreflect.FileDescriptor) (*pluginpb.CodeGeneratorResponse, error) {
	req := &pluginpb.CodeGeneratorRequest{}
	seen := map[string]bool{}
	var walk func(fd protoreflect.FileDescriptor)
	walk = func(fd protoreflect.FileDescriptor) {
		if seen[fd.Path()] {
			return
		}
		seen[fd.Path()] = true
		imports := fd.Imports()
		for i := 0; i < imports.Len(); i++ {
			walk(imports.Get(i).FileDescriptor)
		}
		req.ProtoFile = append(req.ProtoFile, protodesc.ToFileDescriptorProto(fd))
	}
	for _, fd := range files {
		walk(fd)
		req.FileToGenerate = append(req.FileToGenerate, fd.Path())
	}
	plugin, err := protogen.Options{}.New(req)
	if err != nil {
		return nil, err
	}
	if err := generator.Generate(plugin, opts); err != nil {
		return nil, err
	}
	return plugin.Response(), nil
}

func emittedContent(resp *pluginpb.CodeGeneratorResponse) string {
	var sb strings.Builder
	for _, f := range resp.File {
		sb.WriteString(f.GetContent())
		sb.WriteString("\n")
	}
	return sb.String()
}

// fileByName finds a single generated file by its path suffix.
func fileByName(resp *pluginpb.CodeGeneratorResponse, suffix string) string {
	for _, f := range resp.File {
		if strings.HasSuffix(f.GetName(), suffix) {
			return f.GetContent()
		}
	}
	return ""
}

var _ = Describe("generator.Generate", func() {
	It("emits a parser struct and helpers for a single-pattern resource", func() {
		resp, err := runGenerator(nil, simplepb.File_simple_simple_proto)
		Expect(err).NotTo(HaveOccurred())

		out := fileByName(resp, "simple/simple.pb.resource.go")
		Expect(out).To(ContainSubstring("// Code generated by protoc-gen-go-resource. DO NOT EDIT."))
		Expect(out).To(ContainSubstring("package simple"))
		Expect(out).To(ContainSubstring("type ParsedThingName struct {"))
		Expect(out).To(ContainSubstring("ThingID string"))
		Expect(out).To(ContainSubstring("func ParseThingName(s string) (ParsedThingName, error)"))
		Expect(out).To(ContainSubstring("func ParseFullThingName(s string) (ParsedThingName, error)"))
		Expect(out).To(ContainSubstring("func (n ParsedThingName) Name() string"))
		Expect(out).To(ContainSubstring("func (n ParsedThingName) FullName() string"))
		Expect(out).To(ContainSubstring("func (x *Thing) ParseName() (ParsedThingName, error)"))
	})

	It("emits one struct per pattern plus a sealed interface for multi-pattern resources", func() {
		resp, err := runGenerator(nil, multipb.File_multipattern_multipattern_proto)
		Expect(err).NotTo(HaveOccurred())

		out := fileByName(resp, "multipattern/multipattern.pb.resource.go")
		Expect(out).To(ContainSubstring("type ParsedBookName_0 struct"))
		Expect(out).To(ContainSubstring("type ParsedBookName_1 struct"))
		Expect(out).To(ContainSubstring("type ParsedBookName interface {"))
		Expect(out).To(ContainSubstring("mustEmbedParsedBookName()"))
		Expect(out).To(ContainSubstring("func ParseBookName(s string) (ParsedBookName, error)"))
		Expect(out).To(ContainSubstring("func ParseFullBookName(s string) (ParsedBookName, error)"))
		Expect(out).To(ContainSubstring("pattern 0:"))
		Expect(out).To(ContainSubstring("pattern 1:"))
	})

	It("honors name_field when the resource's name lives in a non-default field", func() {
		resp, err := runGenerator(nil, namefieldpb.File_namefield_namefield_proto)
		Expect(err).NotTo(HaveOccurred())

		out := fileByName(resp, "namefield/namefield.pb.resource.go")
		Expect(out).To(ContainSubstring("func (x *Person) ParsePersonName() (ParsedPersonName, error)"))
		Expect(out).To(ContainSubstring("return ParsePersonName(x.PersonName)"))
	})

	It("emits parsers for file-level resource_definition without a message", func() {
		resp, err := runGenerator(nil, externalpb.File_external_external_proto)
		Expect(err).NotTo(HaveOccurred())

		out := fileByName(resp, "external/external.pb.resource.go")
		Expect(out).To(ContainSubstring("type ParsedExternalName struct"))
		Expect(out).To(ContainSubstring("func ParseExternalName(s string) (ParsedExternalName, error)"))
	})

	It("resolves cross-package resource_reference fields to the referent's parser", func() {
		resp, err := runGenerator(nil, refpb.File_reference_reference_proto)
		Expect(err).NotTo(HaveOccurred())

		out := fileByName(resp, "reference/reference.pb.resource.go")
		// same-package reference
		Expect(out).To(ContainSubstring("func (x *Foo) ParseBar() (ParsedBarName, error)"))
		Expect(out).To(ContainSubstring("func (x *Bar) ParseFoo() (ParsedFooName, error)"))
		// cross-package message-level reference
		Expect(out).To(ContainSubstring("func (x *CrossPackage) ParseThingName() (simple.ParsedThingName, error)"))
		// cross-package file-level reference
		Expect(out).To(ContainSubstring("func (x *CrossPackageExternal) ParseExternalName() (external.ParsedExternalName, error)"))
	})

	It("silently skips child_type and wildcard resource references", func() {
		resp, err := runGenerator(nil, refpb.File_reference_reference_proto)
		Expect(err).NotTo(HaveOccurred())

		out := fileByName(resp, "reference/reference.pb.resource.go")
		Expect(out).NotTo(ContainSubstring("ChildTypeIgnored"))
		Expect(out).NotTo(ContainSubstring("WildcardReference"))
	})

	It("matches the checked-in golden output for every fixture package", func() {
		cases := []struct {
			fd   protoreflect.FileDescriptor
			path string
		}{
			{simplepb.File_simple_simple_proto, "simple/simple.pb.resource.go"},
			{multipb.File_multipattern_multipattern_proto, "multipattern/multipattern.pb.resource.go"},
			{namefieldpb.File_namefield_namefield_proto, "namefield/namefield.pb.resource.go"},
			{externalpb.File_external_external_proto, "external/external.pb.resource.go"},
			{refpb.File_reference_reference_proto, "reference/reference.pb.resource.go"},
		}
		for _, tc := range cases {
			resp, err := runGenerator(nil, tc.fd)
			Expect(err).NotTo(HaveOccurred(), tc.path)
			got := fileByName(resp, tc.path)
			Expect(got).NotTo(BeEmpty(), tc.path)

			goldenPath := filepath.Join("testpb", tc.path)
			want, err := os.ReadFile(goldenPath)
			Expect(err).NotTo(HaveOccurred(), tc.path)
			Expect(got).To(Equal(string(want)), tc.path)
		}
	})

	It("emits no file for files without resources or references", func() {
		// The plugin should not produce a .pb.resource.go for a file that has
		// nothing to say. We simulate this by pointing at a descriptor that
		// has no resource annotations — the import of google/api/resource.proto
		// itself is such a file.
		imports := simplepb.File_simple_simple_proto.Imports()
		var resourceProto protoreflect.FileDescriptor
		for i := 0; i < imports.Len(); i++ {
			if imports.Get(i).FileDescriptor.Path() == "google/api/resource.proto" {
				resourceProto = imports.Get(i).FileDescriptor
				break
			}
		}
		Expect(resourceProto).NotTo(BeNil())

		resp, err := runGenerator(nil, resourceProto)
		Expect(err).NotTo(HaveOccurred())
		Expect(emittedContent(resp)).To(BeEmpty())
	})
})

var _ = Describe("generator.Options.Set", func() {
	It("rejects unknown plugin options", func() {
		opts := &generator.Options{}
		Expect(opts.Set("nonsense", "true")).To(MatchError(ContainSubstring("unknown plugin option")))
	})
})
