package generator_test

import (
	"os"
	"path/filepath"
	"strings"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protodesc"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/pluginpb"

	"github.com/protoc-contrib/protoc-gen-go-resource/internal/generator"
	externalpb "github.com/protoc-contrib/protoc-gen-go-resource/internal/generator/testpb/external"
	multipb "github.com/protoc-contrib/protoc-gen-go-resource/internal/generator/testpb/multipattern"
	namefieldpb "github.com/protoc-contrib/protoc-gen-go-resource/internal/generator/testpb/namefield"
	refpb "github.com/protoc-contrib/protoc-gen-go-resource/internal/generator/testpb/reference"
	simplepb "github.com/protoc-contrib/protoc-gen-go-resource/internal/generator/testpb/simple"
	uuidpb "github.com/protoc-contrib/protoc-gen-go-resource/internal/generator/testpb/uuid"
)

// runGenerator builds a CodeGeneratorRequest covering the given file
// descriptors (plus their transitive imports) and runs Generate against it.
// The files passed in are the ones flagged for generation; transitive
// imports are registered with the plugin but not emitted.
func runGenerator(opts *generator.Options, files ...protoreflect.FileDescriptor) (*pluginpb.CodeGeneratorResponse, error) {
	req := &pluginpb.CodeGeneratorRequest{}
	seen := map[string]bool{}
	var walk func(fd protoreflect.FileDescriptor)
	walk = func(fd protoreflect.FileDescriptor) {
		if seen[fd.Path()] {
			return
		}
		seen[fd.Path()] = true
		imports := fd.Imports()
		for i := 0; i < imports.Len(); i++ {
			walk(imports.Get(i).FileDescriptor)
		}
		req.ProtoFile = append(req.ProtoFile, protodesc.ToFileDescriptorProto(fd))
	}
	for _, fd := range files {
		walk(fd)
		req.FileToGenerate = append(req.FileToGenerate, fd.Path())
	}
	plugin, err := protogen.Options{}.New(req)
	if err != nil {
		return nil, err
	}
	if err := generator.Generate(plugin, opts); err != nil {
		return nil, err
	}
	return plugin.Response(), nil
}

func emittedContent(resp *pluginpb.CodeGeneratorResponse) string {
	var sb strings.Builder
	for _, f := range resp.File {
		sb.WriteString(f.GetContent())
		sb.WriteString("\n")
	}
	return sb.String()
}

// fileByName finds a single generated file by its path suffix.
func fileByName(resp *pluginpb.CodeGeneratorResponse, suffix string) string {
	for _, f := range resp.File {
		if strings.HasSuffix(f.GetName(), suffix) {
			return f.GetContent()
		}
	}
	return ""
}

var _ = Describe("generator.Generate", func() {
	It("emits a parser struct and helpers for a single-pattern resource", func() {
		resp, err := runGenerator(nil, simplepb.File_simple_simple_proto)
		Expect(err).NotTo(HaveOccurred())

		out := fileByName(resp, "simple/simple.pb.resource.go")
		Expect(out).To(ContainSubstring("// Code generated by protoc-gen-go-resource. DO NOT EDIT."))
		Expect(out).To(ContainSubstring("package simple"))
		Expect(out).To(ContainSubstring("type ThingName struct {"))
		Expect(out).To(ContainSubstring("ThingID string"))
		Expect(out).To(ContainSubstring("func ParseThingName(s string) (ThingName, error)"))
		Expect(out).To(ContainSubstring("func ParseFullThingName(s string) (ThingName, error)"))
		Expect(out).To(ContainSubstring("func (n ThingName) String() string"))
		Expect(out).To(ContainSubstring("func (n ThingName) FullName() string"))
		Expect(out).To(ContainSubstring("func (n ThingName) MarshalText() ([]byte, error)"))
		Expect(out).To(ContainSubstring("func (n *ThingName) UnmarshalText(b []byte) error"))
		// Name() was dropped in favor of String().
		Expect(out).NotTo(ContainSubstring("func (n ThingName) Name() string"))
		Expect(out).To(ContainSubstring("func (x *Thing) ParseName() (ThingName, error)"))
		// The "Parsed" prefix must not leak into generated identifiers.
		Expect(out).NotTo(ContainSubstring("ParsedThingName"))
	})

	It("emits Parent() returning the matched parent resource's type", func() {
		resp, err := runGenerator(nil, simplepb.File_simple_simple_proto)
		Expect(err).NotTo(HaveOccurred())
		out := fileByName(resp, "simple/simple.pb.resource.go")
		Expect(out).To(ContainSubstring("func (n ProjectThingName) Parent() ProjectName {"))
		Expect(out).To(ContainSubstring("ProjectID: n.ProjectID,"))
		// Top-level resources have no parent → no Parent method.
		Expect(out).NotTo(ContainSubstring("func (n ThingName) Parent()"))
	})

	It("emits one struct per pattern plus a sealed interface for multi-pattern resources", func() {
		resp, err := runGenerator(nil, multipb.File_multipattern_multipattern_proto)
		Expect(err).NotTo(HaveOccurred())

		out := fileByName(resp, "multipattern/multipattern.pb.resource.go")
		// Variants are named after their parent resource — no "_N" suffix
		// when every pattern has a distinct registered parent.
		Expect(out).To(ContainSubstring("type PublisherBookName struct"))
		Expect(out).To(ContainSubstring("type AuthorBookName struct"))
		Expect(out).To(ContainSubstring("type BookName interface {"))
		Expect(out).To(ContainSubstring("mustEmbedBookName()"))
		// The sealed interface includes String() so it satisfies fmt.Stringer.
		Expect(out).To(MatchRegexp(`type BookName interface \{[^}]*String\(\) string`))
		Expect(out).To(ContainSubstring("func ParseBookName(s string) (BookName, error)"))
		Expect(out).To(ContainSubstring("func ParseFullBookName(s string) (BookName, error)"))
		Expect(out).To(ContainSubstring("func ParsePublisherBookName(s string) (PublisherBookName, error)"))
		Expect(out).To(ContainSubstring("func ParseAuthorBookName(s string) (AuthorBookName, error)"))
		Expect(out).To(ContainSubstring("no pattern matches"))
		Expect(out).To(ContainSubstring("errors.Join(errs...)"))
		// Each variant's Parent returns the pattern-specific parent.
		Expect(out).To(ContainSubstring("func (n PublisherBookName) Parent() PublisherName {"))
		Expect(out).To(ContainSubstring("func (n AuthorBookName) Parent() AuthorName {"))
		// No "_N" suffixes in this fixture — every pattern has a distinct parent.
		Expect(out).NotTo(ContainSubstring("BookName_0"))
		Expect(out).NotTo(ContainSubstring("BookName_1"))
		// Per-pattern full parsers would be dead code and should not be emitted.
		Expect(out).NotTo(ContainSubstring("ParsePublisherBookNameFull"))
		Expect(out).NotTo(ContainSubstring("ParseFullPublisherBookName"))
	})

	It("honors name_field when the resource's name lives in a non-default field", func() {
		resp, err := runGenerator(nil, namefieldpb.File_namefield_namefield_proto)
		Expect(err).NotTo(HaveOccurred())

		out := fileByName(resp, "namefield/namefield.pb.resource.go")
		Expect(out).To(ContainSubstring("func (x *Person) ParsePersonName() (PersonName, error)"))
		Expect(out).To(ContainSubstring("return ParsePersonName(x.PersonName)"))
	})

	It("emits parsers for file-level resource_definition without a message", func() {
		resp, err := runGenerator(nil, externalpb.File_external_external_proto)
		Expect(err).NotTo(HaveOccurred())

		out := fileByName(resp, "external/external.pb.resource.go")
		Expect(out).To(ContainSubstring("type ExternalName struct"))
		Expect(out).To(ContainSubstring("func ParseExternalName(s string) (ExternalName, error)"))
	})

	It("resolves cross-package resource_reference fields to the referent's parser", func() {
		resp, err := runGenerator(nil, refpb.File_reference_reference_proto)
		Expect(err).NotTo(HaveOccurred())

		out := fileByName(resp, "reference/reference.pb.resource.go")
		// same-package reference
		Expect(out).To(ContainSubstring("func (x *Foo) ParseBar() (BarName, error)"))
		Expect(out).To(ContainSubstring("func (x *Bar) ParseFoo() (FooName, error)"))
		// cross-package message-level reference
		Expect(out).To(ContainSubstring("func (x *CrossPackage) ParseThingName() (simple.ThingName, error)"))
		// cross-package file-level reference
		Expect(out).To(ContainSubstring("func (x *CrossPackageExternal) ParseExternalName() (external.ExternalName, error)"))
	})

	It("silently skips child_type and wildcard resource references", func() {
		resp, err := runGenerator(nil, refpb.File_reference_reference_proto)
		Expect(err).NotTo(HaveOccurred())

		out := fileByName(resp, "reference/reference.pb.resource.go")
		Expect(out).NotTo(ContainSubstring("ChildTypeIgnored"))
		Expect(out).NotTo(ContainSubstring("WildcardReference"))
	})

	It("matches the checked-in golden output for every fixture package", func() {
		cases := []struct {
			fd   protoreflect.FileDescriptor
			path string
		}{
			{simplepb.File_simple_simple_proto, "simple/simple.pb.resource.go"},
			{multipb.File_multipattern_multipattern_proto, "multipattern/multipattern.pb.resource.go"},
			{namefieldpb.File_namefield_namefield_proto, "namefield/namefield.pb.resource.go"},
			{externalpb.File_external_external_proto, "external/external.pb.resource.go"},
			{refpb.File_reference_reference_proto, "reference/reference.pb.resource.go"},
			{uuidpb.File_uuid_uuid_proto, "uuid/uuid.pb.resource.go"},
		}
		for _, tc := range cases {
			resp, err := runGenerator(nil, tc.fd)
			Expect(err).NotTo(HaveOccurred(), tc.path)
			got := fileByName(resp, tc.path)
			Expect(got).NotTo(BeEmpty(), tc.path)

			goldenPath := filepath.Join("testpb", tc.path)
			want, err := os.ReadFile(goldenPath)
			Expect(err).NotTo(HaveOccurred(), tc.path)
			Expect(got).To(Equal(string(want)), tc.path)
		}
	})

	It("emits no file for files without resources or references", func() {
		// The plugin should not produce a .pb.resource.go for a file that has
		// nothing to say. We simulate this by pointing at a descriptor that
		// has no resource annotations — the import of google/api/resource.proto
		// itself is such a file.
		imports := simplepb.File_simple_simple_proto.Imports()
		var resourceProto protoreflect.FileDescriptor
		for i := 0; i < imports.Len(); i++ {
			if imports.Get(i).FileDescriptor.Path() == "google/api/resource.proto" {
				resourceProto = imports.Get(i).FileDescriptor
				break
			}
		}
		Expect(resourceProto).NotTo(BeNil())

		resp, err := runGenerator(nil, resourceProto)
		Expect(err).NotTo(HaveOccurred())
		Expect(emittedContent(resp)).To(BeEmpty())
	})
})

var _ = Describe("generator.Options.Set", func() {
	It("rejects unknown plugin options", func() {
		opts := &generator.Options{}
		Expect(opts.Set("nonsense", "true")).To(MatchError(ContainSubstring("unknown plugin option")))
	})

	It("accepts allow_unresolved_refs", func() {
		opts := &generator.Options{}
		Expect(opts.Set("allow_unresolved_refs", "true")).To(Succeed())
		Expect(opts.AllowUnresolvedRefs).To(BeTrue())
	})

	It("rejects non-bool values for allow_unresolved_refs", func() {
		opts := &generator.Options{}
		Expect(opts.Set("allow_unresolved_refs", "sure")).To(MatchError(ContainSubstring("invalid value")))
	})
})

var _ = Describe("generator.Generate validation", func() {
	It("emits a runtime guard for empty variable segments", func() {
		resp, err := runGenerator(nil, simplepb.File_simple_simple_proto)
		Expect(err).NotTo(HaveOccurred())
		out := fileByName(resp, "simple/simple.pb.resource.go")
		Expect(out).To(ContainSubstring(`empty value for segment 1`))
	})

	It("emits ParseFullName alongside ParseName on resource messages", func() {
		resp, err := runGenerator(nil, simplepb.File_simple_simple_proto)
		Expect(err).NotTo(HaveOccurred())
		out := fileByName(resp, "simple/simple.pb.resource.go")
		Expect(out).To(ContainSubstring("func (x *Thing) ParseFullName() (ThingName, error)"))
		Expect(out).To(ContainSubstring("return ParseFullThingName(x.Name)"))
	})
})

var _ = Describe("generator.Generate UUID segments", func() {
	It("types a UUID4-annotated segment as uuid.UUID and validates at parse time", func() {
		resp, err := runGenerator(nil, uuidpb.File_uuid_uuid_proto)
		Expect(err).NotTo(HaveOccurred())
		out := fileByName(resp, "uuid/uuid.pb.resource.go")
		Expect(out).To(ContainSubstring(`uuid "github.com/google/uuid"`))
		Expect(out).To(ContainSubstring("CollectionID uuid.UUID"))
		Expect(out).To(ContainSubstring("uuid.Parse(parts[1])"))
		Expect(out).To(ContainSubstring(`fmt.Errorf("parse %q: segment 1: %w", s, err)`))
		// String() renders through uuid.UUID.String() so the struct field
		// can stay typed.
		Expect(out).To(ContainSubstring(`return "collections/" + n.CollectionID.String()`))
	})

	It("flows typed parent ids through Parent() when both resources declare the same UUID segment", func() {
		resp, err := runGenerator(nil, uuidpb.File_uuid_uuid_proto)
		Expect(err).NotTo(HaveOccurred())
		out := fileByName(resp, "uuid/uuid.pb.resource.go")
		Expect(out).To(ContainSubstring("func (n ItemName) Parent() OrganizationName {"))
		Expect(out).To(ContainSubstring("OrganizationID: n.OrganizationID,"))
		Expect(out).To(ContainSubstring("OrganizationID uuid.UUID"))
		Expect(out).To(ContainSubstring("ItemID         uuid.UUID"))
	})
})
