// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: simple/simple.proto

package simple

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Thing exercises a single-segment resource pattern.
type Thing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Thing) Reset() {
	*x = Thing{}
	mi := &file_simple_simple_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Thing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Thing) ProtoMessage() {}

func (x *Thing) ProtoReflect() protoreflect.Message {
	mi := &file_simple_simple_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Thing.ProtoReflect.Descriptor instead.
func (*Thing) Descriptor() ([]byte, []int) {
	return file_simple_simple_proto_rawDescGZIP(), []int{0}
}

func (x *Thing) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Project is the parent of ProjectThing. Declaring it separately lets the
// generator bind ProjectThing.Parent() to ProjectName.
type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_simple_simple_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_simple_simple_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_simple_simple_proto_rawDescGZIP(), []int{1}
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ProjectThing exercises a multi-segment, single-pattern resource. Its parent
// pattern matches Project above, so Parent() returns ProjectName.
type ProjectThing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectThing) Reset() {
	*x = ProjectThing{}
	mi := &file_simple_simple_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectThing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectThing) ProtoMessage() {}

func (x *ProjectThing) ProtoReflect() protoreflect.Message {
	mi := &file_simple_simple_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectThing.ProtoReflect.Descriptor instead.
func (*ProjectThing) Descriptor() ([]byte, []int) {
	return file_simple_simple_proto_rawDescGZIP(), []int{2}
}

func (x *ProjectThing) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_simple_simple_proto protoreflect.FileDescriptor

const file_simple_simple_proto_rawDesc = "" +
	"\n" +
	"\x13simple/simple.proto\x12\ftests.simple\x1a\x19google/api/resource.proto\"C\n" +
	"\x05Thing\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name:&\xeaA#\n" +
	"\x11example.com/Thing\x12\x0ethings/{thing}\"K\n" +
	"\aProject\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name:,\xeaA)\n" +
	"\x13example.com/Project\x12\x12projects/{project}\"d\n" +
	"\fProjectThing\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name:@\xeaA=\n" +
	"\x18example.com/ProjectThing\x12!projects/{project}/things/{thing}BSZQgithub.com/protoc-contrib/protoc-gen-go-resource/internal/generator/testpb/simpleb\x06proto3"

var (
	file_simple_simple_proto_rawDescOnce sync.Once
	file_simple_simple_proto_rawDescData []byte
)

func file_simple_simple_proto_rawDescGZIP() []byte {
	file_simple_simple_proto_rawDescOnce.Do(func() {
		file_simple_simple_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_simple_simple_proto_rawDesc), len(file_simple_simple_proto_rawDesc)))
	})
	return file_simple_simple_proto_rawDescData
}

var file_simple_simple_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_simple_simple_proto_goTypes = []any{
	(*Thing)(nil),        // 0: tests.simple.Thing
	(*Project)(nil),      // 1: tests.simple.Project
	(*ProjectThing)(nil), // 2: tests.simple.ProjectThing
}
var file_simple_simple_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_simple_simple_proto_init() }
func file_simple_simple_proto_init() {
	if File_simple_simple_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_simple_simple_proto_rawDesc), len(file_simple_simple_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_simple_simple_proto_goTypes,
		DependencyIndexes: file_simple_simple_proto_depIdxs,
		MessageInfos:      file_simple_simple_proto_msgTypes,
	}.Build()
	File_simple_simple_proto = out.File
	file_simple_simple_proto_goTypes = nil
	file_simple_simple_proto_depIdxs = nil
}
