// Code generated by protoc-gen-go-resource. DO NOT EDIT.
// source: simple/simple.proto

package simple

import (
	fmt "fmt"
	strings "strings"
)

type ThingName struct {
	ThingID string
}

func ParseThingName(s string) (ThingName, error) {
	parts := strings.Split(s, "/")
	if len(parts) != 2 {
		return ThingName{}, fmt.Errorf("parse %q: bad number of segments, want: 2, got: %d", s, len(parts))
	}
	var out ThingName
	if parts[0] != "things" {
		return ThingName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "things", parts[0])
	}
	if parts[1] == "" {
		return ThingName{}, fmt.Errorf("parse %q: empty value for segment 1", s)
	}
	out.ThingID = parts[1]
	return out, nil
}

func ParseFullThingName(s string) (ThingName, error) {
	if !strings.HasPrefix(s, "//example.com/") {
		return ThingName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//example.com/")
	}
	return ParseThingName(strings.TrimPrefix(s, "//example.com/"))
}

func (n ThingName) Name() string {
	return "things/" + n.ThingID
}

func (n ThingName) FullName() string {
	return "//example.com/" + n.Name()
}

func (n ThingName) String() string {
	return n.Name()
}

type ProjectName struct {
	ProjectID string
}

func ParseProjectName(s string) (ProjectName, error) {
	parts := strings.Split(s, "/")
	if len(parts) != 2 {
		return ProjectName{}, fmt.Errorf("parse %q: bad number of segments, want: 2, got: %d", s, len(parts))
	}
	var out ProjectName
	if parts[0] != "projects" {
		return ProjectName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "projects", parts[0])
	}
	if parts[1] == "" {
		return ProjectName{}, fmt.Errorf("parse %q: empty value for segment 1", s)
	}
	out.ProjectID = parts[1]
	return out, nil
}

func ParseFullProjectName(s string) (ProjectName, error) {
	if !strings.HasPrefix(s, "//example.com/") {
		return ProjectName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//example.com/")
	}
	return ParseProjectName(strings.TrimPrefix(s, "//example.com/"))
}

func (n ProjectName) Name() string {
	return "projects/" + n.ProjectID
}

func (n ProjectName) FullName() string {
	return "//example.com/" + n.Name()
}

func (n ProjectName) String() string {
	return n.Name()
}

type ProjectThingName struct {
	ProjectID string
	ThingID   string
}

func ParseProjectThingName(s string) (ProjectThingName, error) {
	parts := strings.Split(s, "/")
	if len(parts) != 4 {
		return ProjectThingName{}, fmt.Errorf("parse %q: bad number of segments, want: 4, got: %d", s, len(parts))
	}
	var out ProjectThingName
	if parts[0] != "projects" {
		return ProjectThingName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "projects", parts[0])
	}
	if parts[1] == "" {
		return ProjectThingName{}, fmt.Errorf("parse %q: empty value for segment 1", s)
	}
	out.ProjectID = parts[1]
	if parts[2] != "things" {
		return ProjectThingName{}, fmt.Errorf("parse %q: bad segment 2, want: %q, got: %q", s, "things", parts[2])
	}
	if parts[3] == "" {
		return ProjectThingName{}, fmt.Errorf("parse %q: empty value for segment 3", s)
	}
	out.ThingID = parts[3]
	return out, nil
}

func ParseFullProjectThingName(s string) (ProjectThingName, error) {
	if !strings.HasPrefix(s, "//example.com/") {
		return ProjectThingName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//example.com/")
	}
	return ParseProjectThingName(strings.TrimPrefix(s, "//example.com/"))
}

func (n ProjectThingName) Name() string {
	return "projects/" + n.ProjectID + "/things/" + n.ThingID
}

func (n ProjectThingName) FullName() string {
	return "//example.com/" + n.Name()
}

func (n ProjectThingName) String() string {
	return n.Name()
}

func (n ProjectThingName) Parent() ProjectName {
	return ProjectName{
		ProjectID: n.ProjectID,
	}
}

func (x *Thing) ParseName() (ThingName, error) {
	return ParseThingName(x.Name)
}

func (x *Thing) ParseFullName() (ThingName, error) {
	return ParseFullThingName(x.Name)
}

func (x *Project) ParseName() (ProjectName, error) {
	return ParseProjectName(x.Name)
}

func (x *Project) ParseFullName() (ProjectName, error) {
	return ParseFullProjectName(x.Name)
}

func (x *ProjectThing) ParseName() (ProjectThingName, error) {
	return ParseProjectThingName(x.Name)
}

func (x *ProjectThing) ParseFullName() (ProjectThingName, error) {
	return ParseFullProjectThingName(x.Name)
}
