// Code generated by protoc-gen-go-resource. DO NOT EDIT.
// source: simple/simple.proto

package simple

import (
	fmt "fmt"
	strings "strings"
)

type ParsedThingName struct {
	ThingID string
}

func ParseThingName(s string) (ParsedThingName, error) {
	parts := strings.Split(s, "/")
	if len(parts) != 2 {
		return ParsedThingName{}, fmt.Errorf("parse %q: bad number of segments, want: 2, got: %d", s, len(parts))
	}
	var out ParsedThingName
	if parts[0] != "things" {
		return ParsedThingName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "things", parts[0])
	}
	out.ThingID = parts[1]
	return out, nil
}

func ParseFullThingName(s string) (ParsedThingName, error) {
	if !strings.HasPrefix(s, "//example.com/") {
		return ParsedThingName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//example.com/")
	}
	return ParseThingName(strings.TrimPrefix(s, "//example.com/"))
}

func (n ParsedThingName) Name() string {
	return "things/" + n.ThingID
}

func (n ParsedThingName) FullName() string {
	return "//example.com/" + n.Name()
}

type ParsedProjectThingName struct {
	ProjectID string
	ThingID   string
}

func ParseProjectThingName(s string) (ParsedProjectThingName, error) {
	parts := strings.Split(s, "/")
	if len(parts) != 4 {
		return ParsedProjectThingName{}, fmt.Errorf("parse %q: bad number of segments, want: 4, got: %d", s, len(parts))
	}
	var out ParsedProjectThingName
	if parts[0] != "projects" {
		return ParsedProjectThingName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "projects", parts[0])
	}
	out.ProjectID = parts[1]
	if parts[2] != "things" {
		return ParsedProjectThingName{}, fmt.Errorf("parse %q: bad segment 2, want: %q, got: %q", s, "things", parts[2])
	}
	out.ThingID = parts[3]
	return out, nil
}

func ParseFullProjectThingName(s string) (ParsedProjectThingName, error) {
	if !strings.HasPrefix(s, "//example.com/") {
		return ParsedProjectThingName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//example.com/")
	}
	return ParseProjectThingName(strings.TrimPrefix(s, "//example.com/"))
}

func (n ParsedProjectThingName) Name() string {
	return "projects/" + n.ProjectID + "/things/" + n.ThingID
}

func (n ParsedProjectThingName) FullName() string {
	return "//example.com/" + n.Name()
}

func (x *Thing) ParseName() (ParsedThingName, error) {
	return ParseThingName(x.Name)
}

func (x *ProjectThing) ParseName() (ParsedProjectThingName, error) {
	return ParseProjectThingName(x.Name)
}
