// Code generated by protoc-gen-go-resource. DO NOT EDIT.
// source: simple/simple.proto

package simple

import (
	fmt "fmt"
	strings "strings"
)

// ThingName is the parsed form of a "example.com/Thing" resource name (pattern "things/{thing}").
type ThingName struct {
	ThingID string
}

// ParseThingName parses s as ThingName (pattern "things/{thing}").
func ParseThingName(s string) (ThingName, error) {
	parts := strings.Split(s, "/")
	if len(parts) != 2 {
		return ThingName{}, fmt.Errorf("parse %q: bad number of segments, want: 2, got: %d", s, len(parts))
	}
	var out ThingName
	if parts[0] != "things" {
		return ThingName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "things", parts[0])
	}
	if parts[1] == "" {
		return ThingName{}, fmt.Errorf("parse %q: empty value for segment 1", s)
	}
	out.ThingID = parts[1]
	return out, nil
}

// ParseFullThingName parses s as the fully-qualified form of ThingName (prefix "//example.com/").
func ParseFullThingName(s string) (ThingName, error) {
	if !strings.HasPrefix(s, "//example.com/") {
		return ThingName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//example.com/")
	}
	return ParseThingName(strings.TrimPrefix(s, "//example.com/"))
}

// String returns the relative resource name "things/{thing}" and implements fmt.Stringer.
func (n ThingName) String() string {
	return "things/" + n.ThingID
}

// FullName returns the fully-qualified resource name prefixed with "//example.com/".
func (n ThingName) FullName() string {
	return "//example.com/" + n.String()
}

// MarshalText implements encoding.TextMarshaler and emits the relative resource name.
func (n ThingName) MarshalText() ([]byte, error) {
	return []byte(n.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler by parsing b as a relative ThingName.
func (n *ThingName) UnmarshalText(b []byte) error {
	parsed, err := ParseThingName(string(b))
	if err != nil {
		return err
	}
	*n = parsed
	return nil
}

// ProjectName is the parsed form of a "example.com/Project" resource name (pattern "projects/{project}").
type ProjectName struct {
	ProjectID string
}

// ParseProjectName parses s as ProjectName (pattern "projects/{project}").
func ParseProjectName(s string) (ProjectName, error) {
	parts := strings.Split(s, "/")
	if len(parts) != 2 {
		return ProjectName{}, fmt.Errorf("parse %q: bad number of segments, want: 2, got: %d", s, len(parts))
	}
	var out ProjectName
	if parts[0] != "projects" {
		return ProjectName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "projects", parts[0])
	}
	if parts[1] == "" {
		return ProjectName{}, fmt.Errorf("parse %q: empty value for segment 1", s)
	}
	out.ProjectID = parts[1]
	return out, nil
}

// ParseFullProjectName parses s as the fully-qualified form of ProjectName (prefix "//example.com/").
func ParseFullProjectName(s string) (ProjectName, error) {
	if !strings.HasPrefix(s, "//example.com/") {
		return ProjectName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//example.com/")
	}
	return ParseProjectName(strings.TrimPrefix(s, "//example.com/"))
}

// String returns the relative resource name "projects/{project}" and implements fmt.Stringer.
func (n ProjectName) String() string {
	return "projects/" + n.ProjectID
}

// FullName returns the fully-qualified resource name prefixed with "//example.com/".
func (n ProjectName) FullName() string {
	return "//example.com/" + n.String()
}

// MarshalText implements encoding.TextMarshaler and emits the relative resource name.
func (n ProjectName) MarshalText() ([]byte, error) {
	return []byte(n.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler by parsing b as a relative ProjectName.
func (n *ProjectName) UnmarshalText(b []byte) error {
	parsed, err := ParseProjectName(string(b))
	if err != nil {
		return err
	}
	*n = parsed
	return nil
}

// ProjectThingName is the parsed form of a "example.com/ProjectThing" resource name (pattern "projects/{project}/things/{thing}").
type ProjectThingName struct {
	ProjectID string
	ThingID   string
}

// ParseProjectThingName parses s as ProjectThingName (pattern "projects/{project}/things/{thing}").
func ParseProjectThingName(s string) (ProjectThingName, error) {
	parts := strings.Split(s, "/")
	if len(parts) != 4 {
		return ProjectThingName{}, fmt.Errorf("parse %q: bad number of segments, want: 4, got: %d", s, len(parts))
	}
	var out ProjectThingName
	if parts[0] != "projects" {
		return ProjectThingName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "projects", parts[0])
	}
	if parts[1] == "" {
		return ProjectThingName{}, fmt.Errorf("parse %q: empty value for segment 1", s)
	}
	out.ProjectID = parts[1]
	if parts[2] != "things" {
		return ProjectThingName{}, fmt.Errorf("parse %q: bad segment 2, want: %q, got: %q", s, "things", parts[2])
	}
	if parts[3] == "" {
		return ProjectThingName{}, fmt.Errorf("parse %q: empty value for segment 3", s)
	}
	out.ThingID = parts[3]
	return out, nil
}

// ParseFullProjectThingName parses s as the fully-qualified form of ProjectThingName (prefix "//example.com/").
func ParseFullProjectThingName(s string) (ProjectThingName, error) {
	if !strings.HasPrefix(s, "//example.com/") {
		return ProjectThingName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//example.com/")
	}
	return ParseProjectThingName(strings.TrimPrefix(s, "//example.com/"))
}

// String returns the relative resource name "projects/{project}/things/{thing}" and implements fmt.Stringer.
func (n ProjectThingName) String() string {
	return "projects/" + n.ProjectID + "/things/" + n.ThingID
}

// FullName returns the fully-qualified resource name prefixed with "//example.com/".
func (n ProjectThingName) FullName() string {
	return "//example.com/" + n.String()
}

// MarshalText implements encoding.TextMarshaler and emits the relative resource name.
func (n ProjectThingName) MarshalText() ([]byte, error) {
	return []byte(n.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler by parsing b as a relative ProjectThingName.
func (n *ProjectThingName) UnmarshalText(b []byte) error {
	parsed, err := ParseProjectThingName(string(b))
	if err != nil {
		return err
	}
	*n = parsed
	return nil
}

// Parent returns the parent ProjectName derived from this resource's fields.
func (n ProjectThingName) Parent() ProjectName {
	return ProjectName{
		ProjectID: n.ProjectID,
	}
}

// ParseName parses x.Name as ThingName.
func (x *Thing) ParseName() (ThingName, error) {
	return ParseThingName(x.Name)
}

// ParseFullName parses x.Name as ThingName.
func (x *Thing) ParseFullName() (ThingName, error) {
	return ParseFullThingName(x.Name)
}

// ParseName parses x.Name as ProjectName.
func (x *Project) ParseName() (ProjectName, error) {
	return ParseProjectName(x.Name)
}

// ParseFullName parses x.Name as ProjectName.
func (x *Project) ParseFullName() (ProjectName, error) {
	return ParseFullProjectName(x.Name)
}

// ParseName parses x.Name as ProjectThingName.
func (x *ProjectThing) ParseName() (ProjectThingName, error) {
	return ParseProjectThingName(x.Name)
}

// ParseFullName parses x.Name as ProjectThingName.
func (x *ProjectThing) ParseFullName() (ProjectThingName, error) {
	return ParseFullProjectThingName(x.Name)
}
